package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockHolderLatest<M extends BaseStockHolderLatest<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_holder_latest";

	/**
	 * 股票代码
	 */
	public void setStockCode(java.lang.String stockCode) {
		set("stock_code", stockCode);
	}

	/**
	 * 股票代码
	 */
	public java.lang.String getStockCode() {
		return get("stock_code");
	}

	/**
	 * 报告日期
	 */
	public void setReportDate(java.lang.String reportDate) {
		set("report_date", reportDate);
	}

	/**
	 * 报告日期
	 */
	public java.lang.String getReportDate() {
		return get("report_date");
	}

	/**
	 * 十大股东 or 十大流通股东
	 */
	public void setHolderType(java.lang.String holderType) {
		set("holder_type", holderType);
	}

	/**
	 * 十大股东 or 十大流通股东
	 */
	public java.lang.String getHolderType() {
		return get("holder_type");
	}

	/**
	 * 股本性质
	 */
	public void setStockChar(java.lang.String stockChar) {
		set("stock_char", stockChar);
	}

	/**
	 * 股本性质
	 */
	public java.lang.String getStockChar() {
		return get("stock_char");
	}

	/**
	 * 持股数量(股)
	 */
	public void setQty(java.lang.String qty) {
		set("qty", qty);
	}

	/**
	 * 持股数量(股)
	 */
	public java.lang.String getQty() {
		return get("qty");
	}

	/**
	 * 股东名称
	 */
	public void setHolderName(java.lang.String holderName) {
		set("holder_name", holderName);
	}

	/**
	 * 股东名称
	 */
	public java.lang.String getHolderName() {
		return get("holder_name");
	}

	/**
	 * 股东性质
	 */
	public void setHolderChar(java.lang.String holderChar) {
		set("holder_char", holderChar);
	}

	/**
	 * 股东性质
	 */
	public java.lang.String getHolderChar() {
		return get("holder_char");
	}

	/**
	 * 持股比例(%)
	 */
	public void setStockRatio(java.lang.String stockRatio) {
		set("stock_ratio", stockRatio);
	}

	/**
	 * 持股比例(%)
	 */
	public java.lang.String getStockRatio() {
		return get("stock_ratio");
	}

	/**
	 * 持股比例变动
	 */
	public void setStockRatioChange(java.lang.String stockRatioChange) {
		set("stock_ratio_change", stockRatioChange);
	}

	/**
	 * 持股比例变动
	 */
	public java.lang.String getStockRatioChange() {
		return get("stock_ratio_change");
	}

	/**
	 * 较上期持股变动数(股)
	 */
	public void setQtyChange(java.lang.String qtyChange) {
		set("qty_change", qtyChange);
	}

	/**
	 * 较上期持股变动数(股)
	 */
	public java.lang.String getQtyChange() {
		return get("qty_change");
	}

}
