package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRptOpsStatTrend<M extends BaseRptOpsStatTrend<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rpt_ops_stat_trend";

	/**
	 * 时间节点（按月统计）
	 */
	public void setDurTime(java.lang.String durTime) {
		set("dur_time", durTime);
	}

	/**
	 * 时间节点（按月统计）
	 */
	public java.lang.String getDurTime() {
		return get("dur_time");
	}

	/**
	 * 投资者期望指数
	 */
	public void setIei(java.lang.Double iei) {
		set("iei", iei);
	}

	/**
	 * 投资者期望指数
	 */
	public java.lang.Double getIei() {
		return get("iei");
	}

	/**
	 * 投资者满意指数
	 */
	public void setIsi(java.lang.Double isi) {
		set("isi", isi);
	}

	/**
	 * 投资者满意指数
	 */
	public java.lang.Double getIsi() {
		return get("isi");
	}

	/**
	 * 投资者信心指数
	 */
	public void setIci(java.lang.Double ici) {
		set("ici", ici);
	}

	/**
	 * 投资者信心指数
	 */
	public java.lang.Double getIci() {
		return get("ici");
	}

}
