package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmRumor<M extends BasePmRumor<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "pm_rumor";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 流言内容
	 */
	public void setRecord(java.lang.String record) {
		set("record", record);
	}

	/**
	 * 流言内容
	 */
	public java.lang.String getRecord() {
		return get("record");
	}

	/**
	 * 评论数  --不用手动修改
	 */
	public void setCommentNum(java.lang.Integer commentNum) {
		set("comment_num", commentNum);
	}

	/**
	 * 评论数  --不用手动修改
	 */
	public java.lang.Integer getCommentNum() {
		return get("comment_num");
	}

	/**
	 * 点赞数  --不用手动修改
	 */
	public void setDianzNum(java.lang.Integer dianzNum) {
		set("dianz_num", dianzNum);
	}

	/**
	 * 点赞数  --不用手动修改
	 */
	public java.lang.Integer getDianzNum() {
		return get("dianz_num");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
