package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntChgRecord<M extends BaseEntChgRecord<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_chg_record";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 工商变更信息（变更后内容，变更日期，变更项目，企业UUID，变更前内容）
	 */
	public void setRecord(java.lang.String record) {
		set("record", record);
	}

	/**
	 * 工商变更信息（变更后内容，变更日期，变更项目，企业UUID，变更前内容）
	 */
	public java.lang.String getRecord() {
		return get("record");
	}

}
