package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockManageTeam<M extends BaseStockManageTeam<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_manage_team";

	/**
	 * 股票代码
	 */
	public void setStockCode(java.lang.String stockCode) {
		set("stock_code", stockCode);
	}

	/**
	 * 股票代码
	 */
	public java.lang.String getStockCode() {
		return get("stock_code");
	}

	/**
	 * 姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 姓名
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 职位
	 */
	public void setPosition(java.lang.String position) {
		set("position", position);
	}

	/**
	 * 职位
	 */
	public java.lang.String getPosition() {
		return get("position");
	}

	/**
	 * 职位类别
	 */
	public void setPosType(java.lang.String posType) {
		set("pos_type", posType);
	}

	/**
	 * 职位类别
	 */
	public java.lang.String getPosType() {
		return get("pos_type");
	}

	/**
	 * 就职日期
	 */
	public void setPosStartdate(java.lang.String posStartdate) {
		set("pos_startdate", posStartdate);
	}

	/**
	 * 就职日期
	 */
	public java.lang.String getPosStartdate() {
		return get("pos_startdate");
	}

	/**
	 * 离职日期
	 */
	public void setPosEnddate(java.lang.String posEnddate) {
		set("pos_enddate", posEnddate);
	}

	/**
	 * 离职日期
	 */
	public java.lang.String getPosEnddate() {
		return get("pos_enddate");
	}

	/**
	 * 性别
	 */
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	/**
	 * 性别
	 */
	public java.lang.String getSex() {
		return get("sex");
	}

	/**
	 * 国籍
	 */
	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	/**
	 * 国籍
	 */
	public java.lang.String getCountry() {
		return get("country");
	}

	/**
	 * 最高学历
	 */
	public void setEducation(java.lang.String education) {
		set("education", education);
	}

	/**
	 * 最高学历
	 */
	public java.lang.String getEducation() {
		return get("education");
	}

	/**
	 * 出生年份
	 */
	public void setBirthdate(java.lang.String birthdate) {
		set("birthdate", birthdate);
	}

	/**
	 * 出生年份
	 */
	public java.lang.String getBirthdate() {
		return get("birthdate");
	}

	/**
	 * 简介
	 */
	public void setResume(java.lang.String resume) {
		set("resume", resume);
	}

	/**
	 * 简介
	 */
	public java.lang.String getResume() {
		return get("resume");
	}

}
