package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRdsEntMortgages<M extends BaseRdsEntMortgages<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rds_ent_mortgages";

	/**
	 * 企业编码
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业编码
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 企业动产抵押信息（登记编号,状态,登记机关,被担保债权数额,被担保债权种类,债务人履行债务的期限,担保范围,备注,被担保债权概况-种类,被担保债权概况-币种,被担保债权概况-数额,被担保债权概况-担保的范围,被担保债权概况-债务人履行债务的期限,被担保债权概况-备注,注销日期,注销原因,序号,抵押物备注,抵押物所有权归属,抵押物名称,抵押物描述,抵押物序号,抵押权人证照/证件号码,抵押权人序号,抵押权人名称,抵押权人证照/证件类型）
	 */
	public void setRecord(java.lang.String record) {
		set("record", record);
	}

	/**
	 * 企业动产抵押信息（登记编号,状态,登记机关,被担保债权数额,被担保债权种类,债务人履行债务的期限,担保范围,备注,被担保债权概况-种类,被担保债权概况-币种,被担保债权概况-数额,被担保债权概况-担保的范围,被担保债权概况-债务人履行债务的期限,被担保债权概况-备注,注销日期,注销原因,序号,抵押物备注,抵押物所有权归属,抵押物名称,抵押物描述,抵押物序号,抵押权人证照/证件号码,抵押权人序号,抵押权人名称,抵押权人证照/证件类型）
	 */
	public java.lang.String getRecord() {
		return get("record");
	}

}
