package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdEntStock<M extends BaseIdEntStock<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "id_ent_stock";

	/**
	 * UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 股票代码
	 */
	public void setStockCode(java.lang.String stockCode) {
		set("stock_code", stockCode);
	}

	/**
	 * 股票代码
	 */
	public java.lang.String getStockCode() {
		return get("stock_code");
	}

	/**
	 * 公司全称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 公司全称
	 */
	public java.lang.String getName() {
		return get("name");
	}

}
