package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntRelated<M extends BaseEntRelated<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_related";

	/**
	 * 邮箱后缀名
	 */
	public void setMailSuffix(java.lang.String mailSuffix) {
		set("mail_suffix", mailSuffix);
	}

	/**
	 * 邮箱后缀名
	 */
	public java.lang.String getMailSuffix() {
		return get("mail_suffix");
	}

	/**
	 * 企业uuid
	 */
	public void setEntId(java.lang.String entId) {
		set("ent_id", entId);
	}

	/**
	 * 企业uuid
	 */
	public java.lang.String getEntId() {
		return get("ent_id");
	}

	/**
	 * 企业名称
	 */
	public void setEntName(java.lang.String entName) {
		set("ent_name", entName);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getEntName() {
		return get("ent_name");
	}

}
