package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdOrgExitEvent<M extends BaseIdOrgExitEvent<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "id_org_exit_event";

	/**
	 * 机构ID
	 */
	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	/**
	 * 机构ID
	 */
	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

	/**
	 * 退出事件ID，关联dw_basic_data.ops_exit_event_detail的event_id
	 */
	public void setEventId(java.lang.Integer eventId) {
		set("event_id", eventId);
	}

	/**
	 * 退出事件ID，关联dw_basic_data.ops_exit_event_detail的event_id
	 */
	public java.lang.Integer getEventId() {
		return get("event_id");
	}

}
