package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRptOrgerList<M extends BaseRptOrgerList<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rpt_orger_list";

	/**
	 * 自增主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增主键
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 机构投资者
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	/**
	 * 机构投资者
	 */
	public java.lang.String getUserName() {
		return get("user_name");
	}

	/**
	 * 机构
	 */
	public void setOrganizeName(java.lang.String organizeName) {
		set("organize_name", organizeName);
	}

	/**
	 * 机构
	 */
	public java.lang.String getOrganizeName() {
		return get("organize_name");
	}

	/**
	 * 职位
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 职位
	 */
	public java.lang.String getTitle() {
		return get("title");
	}

	/**
	 * 人物简介
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	/**
	 * 人物简介
	 */
	public java.lang.String getDescription() {
		return get("description");
	}

}
