package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRptPeFund<M extends BaseRptPeFund<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rpt_pe_fund";

	/**
	 * 基金名称
	 */
	public void setFundName(java.lang.String fundName) {
		set("fund_name", fundName);
	}

	/**
	 * 基金名称
	 */
	public java.lang.String getFundName() {
		return get("fund_name");
	}

	/**
	 * 基金UUID
	 */
	public void setFundUuid(java.lang.String fundUuid) {
		set("fund_uuid", fundUuid);
	}

	/**
	 * 基金UUID
	 */
	public java.lang.String getFundUuid() {
		return get("fund_uuid");
	}

	/**
	 * 注册时间
	 */
	public void setRegTime(java.lang.String regTime) {
		set("reg_time", regTime);
	}

	/**
	 * 注册时间
	 */
	public java.lang.String getRegTime() {
		return get("reg_time");
	}

	/**
	 * 基金管理机构
	 */
	public void setManager(java.lang.String manager) {
		set("manager", manager);
	}

	/**
	 * 基金管理机构
	 */
	public java.lang.String getManager() {
		return get("manager");
	}

	/**
	 * 基金管理机构UUID
	 */
	public void setMUuid(java.lang.String mUuid) {
		set("m_uuid", mUuid);
	}

	/**
	 * 基金管理机构UUID
	 */
	public java.lang.String getMUuid() {
		return get("m_uuid");
	}

	/**
	 * 基金投资领域
	 */
	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}

	/**
	 * 基金投资领域
	 */
	public java.lang.String getDomain() {
		return get("domain");
	}

}
