package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntAbnormalItem<M extends BaseEntAbnormalItem<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_abnormal_item";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 经营异常-列入原因
	 */
	public void setInReason(java.lang.String inReason) {
		set("in_reason", inReason);
	}

	/**
	 * 经营异常-列入原因
	 */
	public java.lang.String getInReason() {
		return get("in_reason");
	}

	/**
	 * 经营异常-列入时间
	 */
	public void setInDate(java.lang.String inDate) {
		set("in_date", inDate);
	}

	/**
	 * 经营异常-列入时间
	 */
	public java.lang.String getInDate() {
		return get("in_date");
	}

	/**
	 * 经营异常-移出原因
	 */
	public void setOutReason(java.lang.String outReason) {
		set("out_reason", outReason);
	}

	/**
	 * 经营异常-移出原因
	 */
	public java.lang.String getOutReason() {
		return get("out_reason");
	}

	/**
	 * 经营异常-移出时间
	 */
	public void setOutDate(java.lang.String outDate) {
		set("out_date", outDate);
	}

	/**
	 * 经营异常-移出时间
	 */
	public java.lang.String getOutDate() {
		return get("out_date");
	}

	/**
	 * 经营异常-作出决定机关
	 */
	public void setDept(java.lang.String dept) {
		set("dept", dept);
	}

	/**
	 * 经营异常-作出决定机关
	 */
	public java.lang.String getDept() {
		return get("dept");
	}

}
