package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpsCityLnglatInfo<M extends BaseOpsCityLnglatInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ops_city_lnglat_info";

	/**
	 * 
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

	/**
	 * 
	 */
	public java.lang.String getId() {
		return get("id");
	}

	/**
	 * 
	 */
	public void setLng(java.lang.Double lng) {
		set("lng", lng);
	}

	/**
	 * 
	 */
	public java.lang.Double getLng() {
		return get("lng");
	}

	/**
	 * 
	 */
	public void setLat(java.lang.Double lat) {
		set("lat", lat);
	}

	/**
	 * 
	 */
	public java.lang.Double getLat() {
		return get("lat");
	}

	/**
	 * 
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	/**
	 * 
	 */
	public java.lang.String getProvince() {
		return get("province");
	}

	/**
	 * 
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	/**
	 * 
	 */
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
