package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockXsbListMatching<M extends BaseStockXsbListMatching<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_xsb_list_matching";

	/**
	 * 新三板股票代码
	 */
	public void setXsbStockCode(java.lang.String xsbStockCode) {
		set("xsb_stock_code", xsbStockCode);
	}

	/**
	 * 新三板股票代码
	 */
	public java.lang.String getXsbStockCode() {
		return get("xsb_stock_code");
	}

	/**
	 * 上市公司股票代码
	 */
	public void setListStockCode(java.lang.String listStockCode) {
		set("list_stock_code", listStockCode);
	}

	/**
	 * 上市公司股票代码
	 */
	public java.lang.String getListStockCode() {
		return get("list_stock_code");
	}

	/**
	 * 差异度
	 */
	public void setDiff(java.lang.Double diff) {
		set("diff", diff);
	}

	/**
	 * 差异度
	 */
	public java.lang.Double getDiff() {
		return get("diff");
	}

	/**
	 * 是否选取为新三板对标上市公司结果
	 */
	public void setIsXsbMatching(java.lang.Integer isXsbMatching) {
		set("is_xsb_matching", isXsbMatching);
	}

	/**
	 * 是否选取为新三板对标上市公司结果
	 */
	public java.lang.Integer getIsXsbMatching() {
		return get("is_xsb_matching");
	}

	/**
	 * 是否选取为上市公司对标新三板结果
	 */
	public void setIsListMatching(java.lang.Integer isListMatching) {
		set("is_list_matching", isListMatching);
	}

	/**
	 * 是否选取为上市公司对标新三板结果
	 */
	public java.lang.Integer getIsListMatching() {
		return get("is_list_matching");
	}

}
