package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntEquity<M extends BaseEntEquity<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_equity";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 股权出质-登记日期
	 */
	public void setDate(java.lang.String date) {
		set("date", date);
	}

	/**
	 * 股权出质-登记日期
	 */
	public java.lang.String getDate() {
		return get("date");
	}

	/**
	 * 股权出质-登记编号
	 */
	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	/**
	 * 股权出质-登记编号
	 */
	public java.lang.String getNumber() {
		return get("number");
	}

	/**
	 * 股权出质-出质股权数
	 */
	public void setPdgAmount(java.lang.String pdgAmount) {
		set("pdg_amount", pdgAmount);
	}

	/**
	 * 股权出质-出质股权数
	 */
	public java.lang.String getPdgAmount() {
		return get("pdg_amount");
	}

	/**
	 * 股权出质-质权人
	 */
	public void setPdg(java.lang.String pdg) {
		set("pdg", pdg);
	}

	/**
	 * 股权出质-质权人
	 */
	public java.lang.String getPdg() {
		return get("pdg");
	}

	/**
	 * 股权出质-出质人证件号码
	 */
	public void setPdgIdentifyNo(java.lang.String pdgIdentifyNo) {
		set("pdg_identify_no", pdgIdentifyNo);
	}

	/**
	 * 股权出质-出质人证件号码
	 */
	public java.lang.String getPdgIdentifyNo() {
		return get("pdg_identify_no");
	}

	/**
	 * 股权出质-质权公司
	 */
	public void setPw(java.lang.String pw) {
		set("pw", pw);
	}

	/**
	 * 股权出质-质权公司
	 */
	public java.lang.String getPw() {
		return get("pw");
	}

	/**
	 * 股权出质-质权人证件号码
	 */
	public void setPwIdNo(java.lang.String pwIdNo) {
		set("pw_id_no", pwIdNo);
	}

	/**
	 * 股权出质-质权人证件号码
	 */
	public java.lang.String getPwIdNo() {
		return get("pw_id_no");
	}

	/**
	 * 股权出质-股权出质-状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	/**
	 * 股权出质-股权出质-状态
	 */
	public java.lang.String getStatus() {
		return get("status");
	}

	/**
	 * 股权出质-备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	/**
	 * 股权出质-备注
	 */
	public java.lang.String getRemark() {
		return get("remark");
	}

}
