package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmStartupsInfo<M extends BasePmStartupsInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "pm_startups_info";

	/**
	 * 自增主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增主键
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 企业名称
	 */
	public void setEntName(java.lang.String entName) {
		set("ent_name", entName);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getEntName() {
		return get("ent_name");
	}

	/**
	 * UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 产品/商标名称
	 */
	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}

	/**
	 * 产品/商标名称
	 */
	public java.lang.String getBrand() {
		return get("brand");
	}

	/**
	 * 企业相关简介
	 */
	public void setBrief(java.lang.String brief) {
		set("brief", brief);
	}

	/**
	 * 企业相关简介
	 */
	public java.lang.String getBrief() {
		return get("brief");
	}

	/**
	 * 企业评论
	 */
	public void setComments(java.lang.String comments) {
		set("comments", comments);
	}

	/**
	 * 企业评论
	 */
	public java.lang.String getComments() {
		return get("comments");
	}

	/**
	 * 是否为国内项目（0-未知；1-国内；2-国外）
	 */
	public void setIsDomestic(java.lang.String isDomestic) {
		set("is_domestic", isDomestic);
	}

	/**
	 * 是否为国内项目（0-未知；1-国内；2-国外）
	 */
	public java.lang.String getIsDomestic() {
		return get("is_domestic");
	}

	/**
	 * 项目设计行业类型， 对应ops_rdd.ops_category_domain
	 */
	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}

	/**
	 * 项目设计行业类型， 对应ops_rdd.ops_category_domain
	 */
	public java.lang.String getDomain() {
		return get("domain");
	}

}
