package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmIdOrgExitEvent<M extends BasePmIdOrgExitEvent<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "pm_id_org_exit_event";

	/**
	 * 自增ID
	 */
	public void setEventId(java.lang.Integer eventId) {
		set("event_id", eventId);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getEventId() {
		return get("event_id");
	}

	/**
	 * 基金ID
	 */
	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	/**
	 * 基金ID
	 */
	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

}
