package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntBasicInfo<M extends BaseEntBasicInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_basic_info";

	/**
	 * 企业编码
	 */
	public void setEntId(java.lang.String entId) {
		set("ent_id", entId);
	}

	/**
	 * 企业编码
	 */
	public java.lang.String getEntId() {
		return get("ent_id");
	}

	/**
	 * 企业名称
	 */
	public void setEntName(java.lang.String entName) {
		set("ent_name", entName);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getEntName() {
		return get("ent_name");
	}

	/**
	 * 企业类型
	 */
	public void setEconKind(java.lang.String econKind) {
		set("econ_kind", econKind);
	}

	/**
	 * 企业类型
	 */
	public java.lang.String getEconKind() {
		return get("econ_kind");
	}

	/**
	 * 注册资本
	 */
	public void setRegCapital(java.lang.String regCapital) {
		set("reg_capital", regCapital);
	}

	/**
	 * 注册资本
	 */
	public java.lang.String getRegCapital() {
		return get("reg_capital");
	}

	/**
	 * 单位(万人民币元 万美元)
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	/**
	 * 单位(万人民币元 万美元)
	 */
	public java.lang.String getUnit() {
		return get("unit");
	}

	/**
	 * 经营范围
	 */
	public void setBizArea(java.lang.String bizArea) {
		set("biz_area", bizArea);
	}

	/**
	 * 经营范围
	 */
	public java.lang.String getBizArea() {
		return get("biz_area");
	}

	/**
	 * 经营开始时间
	 */
	public void setOptTimeStart(java.lang.String optTimeStart) {
		set("opt_time_start", optTimeStart);
	}

	/**
	 * 经营开始时间
	 */
	public java.lang.String getOptTimeStart() {
		return get("opt_time_start");
	}

	/**
	 * 经营结束时间
	 */
	public void setOptTimeEnd(java.lang.String optTimeEnd) {
		set("opt_time_end", optTimeEnd);
	}

	/**
	 * 经营结束时间
	 */
	public java.lang.String getOptTimeEnd() {
		return get("opt_time_end");
	}

	/**
	 * 登记机关
	 */
	public void setRegAuth(java.lang.String regAuth) {
		set("reg_auth", regAuth);
	}

	/**
	 * 登记机关
	 */
	public java.lang.String getRegAuth() {
		return get("reg_auth");
	}

	/**
	 * 法定代表人
	 */
	public void setLegalPerson(java.lang.String legalPerson) {
		set("legal_person", legalPerson);
	}

	/**
	 * 法定代表人
	 */
	public java.lang.String getLegalPerson() {
		return get("legal_person");
	}

	/**
	 * 发照日期
	 */
	public void setCheckDate(java.lang.String checkDate) {
		set("check_date", checkDate);
	}

	/**
	 * 发照日期
	 */
	public java.lang.String getCheckDate() {
		return get("check_date");
	}

	/**
	 * 开业日期
	 */
	public void setStartDate(java.lang.String startDate) {
		set("start_date", startDate);
	}

	/**
	 * 开业日期
	 */
	public java.lang.String getStartDate() {
		return get("start_date");
	}

	/**
	 * 注销日期
	 */
	public void setEndDate(java.lang.String endDate) {
		set("end_date", endDate);
	}

	/**
	 * 注销日期
	 */
	public java.lang.String getEndDate() {
		return get("end_date");
	}

	/**
	 * 经营状态
	 */
	public void setBizStat(java.lang.String bizStat) {
		set("biz_stat", bizStat);
	}

	/**
	 * 经营状态
	 */
	public java.lang.String getBizStat() {
		return get("biz_stat");
	}

	/**
	 * 组织机构代码
	 */
	public void setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
	}

	/**
	 * 组织机构代码
	 */
	public java.lang.String getOrgCode() {
		return get("org_code");
	}

	/**
	 * 统一社会信用代码
	 */
	public void setCreditCode(java.lang.String creditCode) {
		set("credit_code", creditCode);
	}

	/**
	 * 统一社会信用代码
	 */
	public java.lang.String getCreditCode() {
		return get("credit_code");
	}

	/**
	 * 注册号
	 */
	public void setRegCode(java.lang.String regCode) {
		set("reg_code", regCode);
	}

	/**
	 * 注册号
	 */
	public java.lang.String getRegCode() {
		return get("reg_code");
	}

	/**
	 * 省份
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	/**
	 * 省份
	 */
	public java.lang.String getProvince() {
		return get("province");
	}

	/**
	 * 城市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}

	/**
	 * 城市
	 */
	public java.lang.String getCity() {
		return get("city");
	}

	/**
	 * 电话
	 */
	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	/**
	 * 电话
	 */
	public java.lang.String getTel() {
		return get("tel");
	}

	/**
	 * 邮件
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	/**
	 * 邮件
	 */
	public java.lang.String getEmail() {
		return get("email");
	}

	/**
	 * 注册地址
	 */
	public void setRegAddr(java.lang.String regAddr) {
		set("reg_addr", regAddr);
	}

	/**
	 * 注册地址
	 */
	public java.lang.String getRegAddr() {
		return get("reg_addr");
	}

	/**
	 * 经营地址
	 */
	public void setOperAddr(java.lang.String operAddr) {
		set("oper_addr", operAddr);
	}

	/**
	 * 经营地址
	 */
	public java.lang.String getOperAddr() {
		return get("oper_addr");
	}

	/**
	 * 行业类型
	 */
	public void setPDomain(java.lang.String pDomain) {
		set("p_domain", pDomain);
	}

	/**
	 * 行业类型
	 */
	public java.lang.String getPDomain() {
		return get("p_domain");
	}

	/**
	 * 更新日期
	 */
	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新日期
	 */
	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

}
