package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRptTrader<M extends BaseRptTrader<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rpt_trader";

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 报告写作日期,原始字段 reportDate
	 */
	public void setReportDate(java.util.Date reportDate) {
		set("report_date", reportDate);
	}

	/**
	 * 报告写作日期,原始字段 reportDate
	 */
	public java.util.Date getReportDate() {
		return get("report_date");
	}

	/**
	 * 作者
	 */
	public void setAuthorList(java.lang.String authorList) {
		set("author_list", authorList);
	}

	/**
	 * 作者
	 */
	public java.lang.String getAuthorList() {
		return get("author_list");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return get("title");
	}

	/**
	 * 报告的类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

	/**
	 * 报告的类型
	 */
	public java.lang.String getType() {
		return get("type");
	}

	/**
	 * 附件本地存储地址
	 */
	public void setAttachment(java.lang.String attachment) {
		set("attachment", attachment);
	}

	/**
	 * 附件本地存储地址
	 */
	public java.lang.String getAttachment() {
		return get("attachment");
	}

}
