package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdCategory<M extends BaseIdCategory<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "id_category";

	/**
	 * 基础分类ID
	 */
	public void setBizId(java.lang.String bizId) {
		set("biz_id", bizId);
	}

	/**
	 * 基础分类ID
	 */
	public java.lang.String getBizId() {
		return get("biz_id");
	}

	/**
	 * 基础分类ID-名称
	 */
	public void setBiz(java.lang.String biz) {
		set("biz", biz);
	}

	/**
	 * 基础分类ID-名称
	 */
	public java.lang.String getBiz() {
		return get("biz");
	}

	/**
	 * 关注领域-名称
	 */
	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}

	/**
	 * 关注领域-名称
	 */
	public java.lang.String getDomain() {
		return get("domain");
	}

	/**
	 * 媒体类型-名称
	 */
	public void setMedia(java.lang.String media) {
		set("media", media);
	}

	/**
	 * 媒体类型-名称
	 */
	public java.lang.String getMedia() {
		return get("media");
	}

}
