package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockFeatureAllScaled<M extends BaseStockFeatureAllScaled<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_feature_all_scaled";

	/**
	 * 股票代码
	 */
	public void setStockCode(java.lang.String stockCode) {
		set("stock_code", stockCode);
	}

	/**
	 * 股票代码
	 */
	public java.lang.String getStockCode() {
		return get("stock_code");
	}

	/**
	 * 企业名称
	 */
	public void setCnName(java.lang.String cnName) {
		set("cn_name", cnName);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getCnName() {
		return get("cn_name");
	}

	/**
	 * 0-沪深A股，1-新三板
	 */
	public void setStockType(java.lang.Long stockType) {
		set("stock_type", stockType);
	}

	/**
	 * 0-沪深A股，1-新三板
	 */
	public java.lang.Long getStockType() {
		return get("stock_type");
	}

	/**
	 * 证监会行业
	 */
	public void setCsrcIndustry(java.lang.String csrcIndustry) {
		set("csrc_industry", csrcIndustry);
	}

	/**
	 * 证监会行业
	 */
	public java.lang.String getCsrcIndustry() {
		return get("csrc_industry");
	}

	/**
	 * 东财行业
	 */
	public void setEmIndustry(java.lang.String emIndustry) {
		set("em_industry", emIndustry);
	}

	/**
	 * 东财行业
	 */
	public java.lang.String getEmIndustry() {
		return get("em_industry");
	}

	/**
	 * topic model 类别
	 */
	public void setTopicIndustry(java.lang.Long topicIndustry) {
		set("topic_industry", topicIndustry);
	}

	/**
	 * topic model 类别
	 */
	public java.lang.Long getTopicIndustry() {
		return get("topic_industry");
	}

	/**
	 * 省份
	 */
	public void setProv(java.lang.String prov) {
		set("prov", prov);
	}

	/**
	 * 省份
	 */
	public java.lang.String getProv() {
		return get("prov");
	}

	/**
	 * 是否发达省份，北京 上海 广东 江苏 山东 浙江
	 */
	public void setIsDev(java.lang.Long isDev) {
		set("is_dev", isDev);
	}

	/**
	 * 是否发达省份，北京 上海 广东 江苏 山东 浙江
	 */
	public java.lang.Long getIsDev() {
		return get("is_dev");
	}

	/**
	 * 实际控制人是否为CEO（总经理）
	 */
	public void setChairmanCumCeo(java.lang.Long chairmanCumCeo) {
		set("chairman_cum_ceo", chairmanCumCeo);
	}

	/**
	 * 实际控制人是否为CEO（总经理）
	 */
	public java.lang.Long getChairmanCumCeo() {
		return get("chairman_cum_ceo");
	}

	/**
	 * 是否国资背景（不精确）
	 */
	public void setIsStateHold(java.lang.Long isStateHold) {
		set("is_state_hold", isStateHold);
	}

	/**
	 * 是否国资背景（不精确）
	 */
	public java.lang.Long getIsStateHold() {
		return get("is_state_hold");
	}

	/**
	 * 控股股东持股比例
	 */
	public void setTop1Hold(java.lang.Double top1Hold) {
		set("top1_hold", top1Hold);
	}

	/**
	 * 控股股东持股比例
	 */
	public java.lang.Double getTop1Hold() {
		return get("top1_hold");
	}

	/**
	 * 十大股东持股比例
	 */
	public void setTop10Hold(java.lang.Double top10Hold) {
		set("top10_hold", top10Hold);
	}

	/**
	 * 十大股东持股比例
	 */
	public java.lang.Double getTop10Hold() {
		return get("top10_hold");
	}

	/**
	 * 股权集中度
	 */
	public void setShareConc(java.lang.Double shareConc) {
		set("share_conc", shareConc);
	}

	/**
	 * 股权集中度
	 */
	public java.lang.Double getShareConc() {
		return get("share_conc");
	}

	/**
	 * 股权制衡度
	 */
	public void setShareBalance(java.lang.Double shareBalance) {
		set("share_balance", shareBalance);
	}

	/**
	 * 股权制衡度
	 */
	public java.lang.Double getShareBalance() {
		return get("share_balance");
	}

	/**
	 * 个人十大股东持股比例
	 */
	public void setPersonHold(java.lang.Double personHold) {
		set("person_hold", personHold);
	}

	/**
	 * 个人十大股东持股比例
	 */
	public java.lang.Double getPersonHold() {
		return get("person_hold");
	}

	/**
	 * CEO学历 1-博士 2-硕士 3-本科 4-专科 0-其它
	 */
	public void setCeoEducation(java.lang.Long ceoEducation) {
		set("ceo_education", ceoEducation);
	}

	/**
	 * CEO学历 1-博士 2-硕士 3-本科 4-专科 0-其它
	 */
	public java.lang.Long getCeoEducation() {
		return get("ceo_education");
	}

	/**
	 * CEO年龄
	 */
	public void setCeoAge(java.lang.Long ceoAge) {
		set("ceo_age", ceoAge);
	}

	/**
	 * CEO年龄
	 */
	public java.lang.Long getCeoAge() {
		return get("ceo_age");
	}

	/**
	 * 市盈率
	 */
	public void setPe(java.lang.Double pe) {
		set("pe", pe);
	}

	/**
	 * 市盈率
	 */
	public java.lang.Double getPe() {
		return get("pe");
	}

	/**
	 * 市净率
	 */
	public void setPb(java.lang.Double pb) {
		set("pb", pb);
	}

	/**
	 * 市净率
	 */
	public java.lang.Double getPb() {
		return get("pb");
	}

	/**
	 * 市销率
	 */
	public void setPs(java.lang.Double ps) {
		set("ps", ps);
	}

	/**
	 * 市销率
	 */
	public java.lang.Double getPs() {
		return get("ps");
	}

	/**
	 * 总股本（万股）
	 */
	public void setTotalStock(java.lang.Double totalStock) {
		set("total_stock", totalStock);
	}

	/**
	 * 总股本（万股）
	 */
	public java.lang.Double getTotalStock() {
		return get("total_stock");
	}

	/**
	 * 市值（亿元）
	 */
	public void setMarketCap(java.lang.Double marketCap) {
		set("market_cap", marketCap);
	}

	/**
	 * 市值（亿元）
	 */
	public java.lang.Double getMarketCap() {
		return get("market_cap");
	}

	/**
	 * 净利润(元)
	 */
	public void setNetProfit(java.lang.Double netProfit) {
		set("net_profit", netProfit);
	}

	/**
	 * 净利润(元)
	 */
	public java.lang.Double getNetProfit() {
		return get("net_profit");
	}

	/**
	 * 营业利润-同比增长(%)
	 */
	public void setOptProfitGrowth(java.lang.Double optProfitGrowth) {
		set("opt_profit_growth", optProfitGrowth);
	}

	/**
	 * 营业利润-同比增长(%)
	 */
	public java.lang.Double getOptProfitGrowth() {
		return get("opt_profit_growth");
	}

	/**
	 * 总资产净利率(%)
	 */
	public void setNetProfitOnAsset(java.lang.Double netProfitOnAsset) {
		set("net_profit_on_asset", netProfitOnAsset);
	}

	/**
	 * 总资产净利率(%)
	 */
	public java.lang.Double getNetProfitOnAsset() {
		return get("net_profit_on_asset");
	}

	/**
	 * 营业利润(元)
	 */
	public void setOptProfit(java.lang.Double optProfit) {
		set("opt_profit", optProfit);
	}

	/**
	 * 营业利润(元)
	 */
	public java.lang.Double getOptProfit() {
		return get("opt_profit");
	}

	/**
	 * 资产总计(元)
	 */
	public void setTotalAsset(java.lang.Double totalAsset) {
		set("total_asset", totalAsset);
	}

	/**
	 * 资产总计(元)
	 */
	public java.lang.Double getTotalAsset() {
		return get("total_asset");
	}

	/**
	 * 利润总额(元)
	 */
	public void setProfit(java.lang.Double profit) {
		set("profit", profit);
	}

	/**
	 * 利润总额(元)
	 */
	public java.lang.Double getProfit() {
		return get("profit");
	}

	/**
	 * 利润总额-同比增长(%)
	 */
	public void setProfitGrowth(java.lang.Double profitGrowth) {
		set("profit_growth", profitGrowth);
	}

	/**
	 * 利润总额-同比增长(%)
	 */
	public java.lang.Double getProfitGrowth() {
		return get("profit_growth");
	}

	/**
	 * 资产总计-相对年初增长(%)
	 */
	public void setTotalAssetGrowth(java.lang.Double totalAssetGrowth) {
		set("total_asset_growth", totalAssetGrowth);
	}

	/**
	 * 资产总计-相对年初增长(%)
	 */
	public java.lang.Double getTotalAssetGrowth() {
		return get("total_asset_growth");
	}

	/**
	 * 归属母公司股东的权益／负债合计(%)
	 */
	public void setHolderEquityOnLiab(java.lang.Double holderEquityOnLiab) {
		set("holder_equity_on_liab", holderEquityOnLiab);
	}

	/**
	 * 归属母公司股东的权益／负债合计(%)
	 */
	public java.lang.Double getHolderEquityOnLiab() {
		return get("holder_equity_on_liab");
	}

	/**
	 * 资产负债率(%)
	 */
	public void setLiabRatio(java.lang.Double liabRatio) {
		set("liab_ratio", liabRatio);
	}

	/**
	 * 资产负债率(%)
	 */
	public java.lang.Double getLiabRatio() {
		return get("liab_ratio");
	}

	/**
	 * 营业收入(元)
	 */
	public void setOptIncome(java.lang.Double optIncome) {
		set("opt_income", optIncome);
	}

	/**
	 * 营业收入(元)
	 */
	public java.lang.Double getOptIncome() {
		return get("opt_income");
	}

	/**
	 * 总资产周转率(次)
	 */
	public void setAssetTurnover(java.lang.Double assetTurnover) {
		set("asset_turnover", assetTurnover);
	}

	/**
	 * 总资产周转率(次)
	 */
	public java.lang.Double getAssetTurnover() {
		return get("asset_turnover");
	}

	/**
	 * 净利润／营业总收入(%)
	 */
	public void setNetProfitOnIncome(java.lang.Double netProfitOnIncome) {
		set("net_profit_on_income", netProfitOnIncome);
	}

	/**
	 * 净利润／营业总收入(%)
	 */
	public java.lang.Double getNetProfitOnIncome() {
		return get("net_profit_on_income");
	}

	/**
	 * 营业利润／营业总收入(%)
	 */
	public void setOptProfitOnIncome(java.lang.Double optProfitOnIncome) {
		set("opt_profit_on_income", optProfitOnIncome);
	}

	/**
	 * 营业利润／营业总收入(%)
	 */
	public java.lang.Double getOptProfitOnIncome() {
		return get("opt_profit_on_income");
	}

	/**
	 * 销售净利率(%)
	 */
	public void setNetProfitMargin(java.lang.Double netProfitMargin) {
		set("net_profit_margin", netProfitMargin);
	}

	/**
	 * 销售净利率(%)
	 */
	public java.lang.Double getNetProfitMargin() {
		return get("net_profit_margin");
	}

	/**
	 * 管理费用／营业总收入(%)
	 */
	public void setMaFeeOnIncome(java.lang.Double maFeeOnIncome) {
		set("ma_fee_on_income", maFeeOnIncome);
	}

	/**
	 * 管理费用／营业总收入(%)
	 */
	public java.lang.Double getMaFeeOnIncome() {
		return get("ma_fee_on_income");
	}

	/**
	 * 营业周期(天)
	 */
	public void setTradeCycle(java.lang.Double tradeCycle) {
		set("trade_cycle", tradeCycle);
	}

	/**
	 * 营业周期(天)
	 */
	public java.lang.Double getTradeCycle() {
		return get("trade_cycle");
	}

	/**
	 * 存货周转天数(天)
	 */
	public void setDaysInInventory(java.lang.Double daysInInventory) {
		set("days_in_inventory", daysInInventory);
	}

	/**
	 * 存货周转天数(天)
	 */
	public java.lang.Double getDaysInInventory() {
		return get("days_in_inventory");
	}

	/**
	 * 带息债务／全部投入资本(%)
	 */
	public void setInterestLiabOnCapital(java.lang.Double interestLiabOnCapital) {
		set("interest_liab_on_capital", interestLiabOnCapital);
	}

	/**
	 * 带息债务／全部投入资本(%)
	 */
	public java.lang.Double getInterestLiabOnCapital() {
		return get("interest_liab_on_capital");
	}

	/**
	 * 流动资产／总资产(%)
	 */
	public void setCurrentAssetRatio(java.lang.Double currentAssetRatio) {
		set("current_asset_ratio", currentAssetRatio);
	}

	/**
	 * 流动资产／总资产(%)
	 */
	public java.lang.Double getCurrentAssetRatio() {
		return get("current_asset_ratio");
	}

	/**
	 * 有形资产／总资产(%)
	 */
	public void setTangibleAssetRatio(java.lang.Double tangibleAssetRatio) {
		set("tangible_asset_ratio", tangibleAssetRatio);
	}

	/**
	 * 有形资产／总资产(%)
	 */
	public java.lang.Double getTangibleAssetRatio() {
		return get("tangible_asset_ratio");
	}

	/**
	 * 总资产报酬率(%)
	 */
	public void setRoa(java.lang.Double roa) {
		set("roa", roa);
	}

	/**
	 * 总资产报酬率(%)
	 */
	public java.lang.Double getRoa() {
		return get("roa");
	}

	/**
	 * 非流动资产／总资产(%)
	 */
	public void setNonCurrentAssetRatio(java.lang.Double nonCurrentAssetRatio) {
		set("non_current_asset_ratio", nonCurrentAssetRatio);
	}

	/**
	 * 非流动资产／总资产(%)
	 */
	public java.lang.Double getNonCurrentAssetRatio() {
		return get("non_current_asset_ratio");
	}

	/**
	 * 有形资产／负债合计(%)
	 */
	public void setTangibleAssetOnLiab(java.lang.Double tangibleAssetOnLiab) {
		set("tangible_asset_on_liab", tangibleAssetOnLiab);
	}

	/**
	 * 有形资产／负债合计(%)
	 */
	public java.lang.Double getTangibleAssetOnLiab() {
		return get("tangible_asset_on_liab");
	}

	/**
	 * 流动负债／负债合计(%)
	 */
	public void setCurrentLiabRatio(java.lang.Double currentLiabRatio) {
		set("current_liab_ratio", currentLiabRatio);
	}

	/**
	 * 流动负债／负债合计(%)
	 */
	public java.lang.Double getCurrentLiabRatio() {
		return get("current_liab_ratio");
	}

	/**
	 * 销售毛利率(%)
	 */
	public void setGrossProfitMargin(java.lang.Double grossProfitMargin) {
		set("gross_profit_margin", grossProfitMargin);
	}

	/**
	 * 销售毛利率(%)
	 */
	public java.lang.Double getGrossProfitMargin() {
		return get("gross_profit_margin");
	}

	/**
	 * 营业总成本／营业总收入(%)
	 */
	public void setOptCostOnIncome(java.lang.Double optCostOnIncome) {
		set("opt_cost_on_income", optCostOnIncome);
	}

	/**
	 * 营业总成本／营业总收入(%)
	 */
	public java.lang.Double getOptCostOnIncome() {
		return get("opt_cost_on_income");
	}

	/**
	 * 投入资本回报率(%)
	 */
	public void setRoic(java.lang.Double roic) {
		set("roic", roic);
	}

	/**
	 * 投入资本回报率(%)
	 */
	public java.lang.Double getRoic() {
		return get("roic");
	}

	/**
	 * 营业收入-同比增长(%)
	 */
	public void setOptIncomeGrowth(java.lang.Double optIncomeGrowth) {
		set("opt_income_growth", optIncomeGrowth);
	}

	/**
	 * 营业收入-同比增长(%)
	 */
	public java.lang.Double getOptIncomeGrowth() {
		return get("opt_income_growth");
	}

	/**
	 * 净资产收益率-年化(%)
	 */
	public void setRoe(java.lang.Double roe) {
		set("roe", roe);
	}

	/**
	 * 净资产收益率-年化(%)
	 */
	public java.lang.Double getRoe() {
		return get("roe");
	}

}
