package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockFeatureParameter<M extends BaseStockFeatureParameter<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_feature_parameter";

	/**
	 * topic model 类别
	 */
	public void setTopicIndustry(java.lang.Long topicIndustry) {
		set("topic_industry", topicIndustry);
	}

	/**
	 * topic model 类别
	 */
	public java.lang.Long getTopicIndustry() {
		return get("topic_industry");
	}

	/**
	 * 0-沪深A股，1-新三板
	 */
	public void setStockType(java.lang.Long stockType) {
		set("stock_type", stockType);
	}

	/**
	 * 0-沪深A股，1-新三板
	 */
	public java.lang.Long getStockType() {
		return get("stock_type");
	}

	/**
	 * 均值-控股股东持股比例
	 */
	public void setAvgTop1Hold(java.lang.Double avgTop1Hold) {
		set("avg_top1_hold", avgTop1Hold);
	}

	/**
	 * 均值-控股股东持股比例
	 */
	public java.lang.Double getAvgTop1Hold() {
		return get("avg_top1_hold");
	}

	/**
	 * 均值-十大股东持股比例
	 */
	public void setAvgTop10Hold(java.lang.Double avgTop10Hold) {
		set("avg_top10_hold", avgTop10Hold);
	}

	/**
	 * 均值-十大股东持股比例
	 */
	public java.lang.Double getAvgTop10Hold() {
		return get("avg_top10_hold");
	}

	/**
	 * 均值-股权集中度
	 */
	public void setAvgShareConc(java.lang.Double avgShareConc) {
		set("avg_share_conc", avgShareConc);
	}

	/**
	 * 均值-股权集中度
	 */
	public java.lang.Double getAvgShareConc() {
		return get("avg_share_conc");
	}

	/**
	 * 均值-股权制衡度
	 */
	public void setAvgShareBalance(java.lang.Double avgShareBalance) {
		set("avg_share_balance", avgShareBalance);
	}

	/**
	 * 均值-股权制衡度
	 */
	public java.lang.Double getAvgShareBalance() {
		return get("avg_share_balance");
	}

	/**
	 * 均值-个人十大股东持股比例
	 */
	public void setAvgPersonHold(java.lang.Double avgPersonHold) {
		set("avg_person_hold", avgPersonHold);
	}

	/**
	 * 均值-个人十大股东持股比例
	 */
	public java.lang.Double getAvgPersonHold() {
		return get("avg_person_hold");
	}

	/**
	 * 均值-CEO学历 1-博士 2-硕士 3-本科 4-专科 0-其它
	 */
	public void setAvgCeoEducation(java.lang.Long avgCeoEducation) {
		set("avg_ceo_education", avgCeoEducation);
	}

	/**
	 * 均值-CEO学历 1-博士 2-硕士 3-本科 4-专科 0-其它
	 */
	public java.lang.Long getAvgCeoEducation() {
		return get("avg_ceo_education");
	}

	/**
	 * 均值-CEO年龄
	 */
	public void setAvgCeoAge(java.lang.Long avgCeoAge) {
		set("avg_ceo_age", avgCeoAge);
	}

	/**
	 * 均值-CEO年龄
	 */
	public java.lang.Long getAvgCeoAge() {
		return get("avg_ceo_age");
	}

	/**
	 * 均值-市盈率
	 */
	public void setAvgPe(java.lang.Double avgPe) {
		set("avg_pe", avgPe);
	}

	/**
	 * 均值-市盈率
	 */
	public java.lang.Double getAvgPe() {
		return get("avg_pe");
	}

	/**
	 * 均值-市净率
	 */
	public void setAvgPb(java.lang.Double avgPb) {
		set("avg_pb", avgPb);
	}

	/**
	 * 均值-市净率
	 */
	public java.lang.Double getAvgPb() {
		return get("avg_pb");
	}

	/**
	 * 均值-市销率
	 */
	public void setAvgPs(java.lang.Double avgPs) {
		set("avg_ps", avgPs);
	}

	/**
	 * 均值-市销率
	 */
	public java.lang.Double getAvgPs() {
		return get("avg_ps");
	}

	/**
	 * 均值-总股本（万股）
	 */
	public void setAvgTotalStock(java.lang.Double avgTotalStock) {
		set("avg_total_stock", avgTotalStock);
	}

	/**
	 * 均值-总股本（万股）
	 */
	public java.lang.Double getAvgTotalStock() {
		return get("avg_total_stock");
	}

	/**
	 * 均值-市值（亿元）
	 */
	public void setAvgMarketCap(java.lang.Double avgMarketCap) {
		set("avg_market_cap", avgMarketCap);
	}

	/**
	 * 均值-市值（亿元）
	 */
	public java.lang.Double getAvgMarketCap() {
		return get("avg_market_cap");
	}

	/**
	 * 均值-净利润(元)
	 */
	public void setAvgNetProfit(java.lang.Double avgNetProfit) {
		set("avg_net_profit", avgNetProfit);
	}

	/**
	 * 均值-净利润(元)
	 */
	public java.lang.Double getAvgNetProfit() {
		return get("avg_net_profit");
	}

	/**
	 * 均值-营业利润-同比增长(%)
	 */
	public void setAvgOptProfitGrowth(java.lang.Double avgOptProfitGrowth) {
		set("avg_opt_profit_growth", avgOptProfitGrowth);
	}

	/**
	 * 均值-营业利润-同比增长(%)
	 */
	public java.lang.Double getAvgOptProfitGrowth() {
		return get("avg_opt_profit_growth");
	}

	/**
	 * 均值-总资产净利率(%)
	 */
	public void setAvgNetProfitOnAsset(java.lang.Double avgNetProfitOnAsset) {
		set("avg_net_profit_on_asset", avgNetProfitOnAsset);
	}

	/**
	 * 均值-总资产净利率(%)
	 */
	public java.lang.Double getAvgNetProfitOnAsset() {
		return get("avg_net_profit_on_asset");
	}

	/**
	 * 均值-营业利润(元)
	 */
	public void setAvgOptProfit(java.lang.Double avgOptProfit) {
		set("avg_opt_profit", avgOptProfit);
	}

	/**
	 * 均值-营业利润(元)
	 */
	public java.lang.Double getAvgOptProfit() {
		return get("avg_opt_profit");
	}

	/**
	 * 均值-资产总计(元)
	 */
	public void setAvgTotalAsset(java.lang.Double avgTotalAsset) {
		set("avg_total_asset", avgTotalAsset);
	}

	/**
	 * 均值-资产总计(元)
	 */
	public java.lang.Double getAvgTotalAsset() {
		return get("avg_total_asset");
	}

	/**
	 * 均值-利润总额(元)
	 */
	public void setAvgProfit(java.lang.Double avgProfit) {
		set("avg_profit", avgProfit);
	}

	/**
	 * 均值-利润总额(元)
	 */
	public java.lang.Double getAvgProfit() {
		return get("avg_profit");
	}

	/**
	 * 均值-利润总额-同比增长(%)
	 */
	public void setAvgProfitGrowth(java.lang.Double avgProfitGrowth) {
		set("avg_profit_growth", avgProfitGrowth);
	}

	/**
	 * 均值-利润总额-同比增长(%)
	 */
	public java.lang.Double getAvgProfitGrowth() {
		return get("avg_profit_growth");
	}

	/**
	 * 均值-资产总计-相对年初增长(%)
	 */
	public void setAvgTotalAssetGrowth(java.lang.Double avgTotalAssetGrowth) {
		set("avg_total_asset_growth", avgTotalAssetGrowth);
	}

	/**
	 * 均值-资产总计-相对年初增长(%)
	 */
	public java.lang.Double getAvgTotalAssetGrowth() {
		return get("avg_total_asset_growth");
	}

	/**
	 * 均值-归属母公司股东的权益／负债合计(%)
	 */
	public void setAvgHolderEquityOnLiab(java.lang.Double avgHolderEquityOnLiab) {
		set("avg_holder_equity_on_liab", avgHolderEquityOnLiab);
	}

	/**
	 * 均值-归属母公司股东的权益／负债合计(%)
	 */
	public java.lang.Double getAvgHolderEquityOnLiab() {
		return get("avg_holder_equity_on_liab");
	}

	/**
	 * 均值-资产负债率(%)
	 */
	public void setAvgLiabRatio(java.lang.Double avgLiabRatio) {
		set("avg_liab_ratio", avgLiabRatio);
	}

	/**
	 * 均值-资产负债率(%)
	 */
	public java.lang.Double getAvgLiabRatio() {
		return get("avg_liab_ratio");
	}

	/**
	 * 均值-营业收入(元)
	 */
	public void setAvgOptIncome(java.lang.Double avgOptIncome) {
		set("avg_opt_income", avgOptIncome);
	}

	/**
	 * 均值-营业收入(元)
	 */
	public java.lang.Double getAvgOptIncome() {
		return get("avg_opt_income");
	}

	/**
	 * 均值-总资产周转率(次)
	 */
	public void setAvgAssetTurnover(java.lang.Double avgAssetTurnover) {
		set("avg_asset_turnover", avgAssetTurnover);
	}

	/**
	 * 均值-总资产周转率(次)
	 */
	public java.lang.Double getAvgAssetTurnover() {
		return get("avg_asset_turnover");
	}

	/**
	 * 均值-净利润／营业总收入(%)
	 */
	public void setAvgNetProfitOnIncome(java.lang.Double avgNetProfitOnIncome) {
		set("avg_net_profit_on_income", avgNetProfitOnIncome);
	}

	/**
	 * 均值-净利润／营业总收入(%)
	 */
	public java.lang.Double getAvgNetProfitOnIncome() {
		return get("avg_net_profit_on_income");
	}

	/**
	 * 均值-营业利润／营业总收入(%)
	 */
	public void setAvgOptProfitOnIncome(java.lang.Double avgOptProfitOnIncome) {
		set("avg_opt_profit_on_income", avgOptProfitOnIncome);
	}

	/**
	 * 均值-营业利润／营业总收入(%)
	 */
	public java.lang.Double getAvgOptProfitOnIncome() {
		return get("avg_opt_profit_on_income");
	}

	/**
	 * 均值-销售净利率(%)
	 */
	public void setAvgNetProfitMargin(java.lang.Double avgNetProfitMargin) {
		set("avg_net_profit_margin", avgNetProfitMargin);
	}

	/**
	 * 均值-销售净利率(%)
	 */
	public java.lang.Double getAvgNetProfitMargin() {
		return get("avg_net_profit_margin");
	}

	/**
	 * 均值-管理费用／营业总收入(%)
	 */
	public void setAvgMaFeeOnIncome(java.lang.Double avgMaFeeOnIncome) {
		set("avg_ma_fee_on_income", avgMaFeeOnIncome);
	}

	/**
	 * 均值-管理费用／营业总收入(%)
	 */
	public java.lang.Double getAvgMaFeeOnIncome() {
		return get("avg_ma_fee_on_income");
	}

	/**
	 * 均值-营业周期(天)
	 */
	public void setAvgTradeCycle(java.lang.Double avgTradeCycle) {
		set("avg_trade_cycle", avgTradeCycle);
	}

	/**
	 * 均值-营业周期(天)
	 */
	public java.lang.Double getAvgTradeCycle() {
		return get("avg_trade_cycle");
	}

	/**
	 * 均值-存货周转天数(天)
	 */
	public void setAvgDaysInInventory(java.lang.Double avgDaysInInventory) {
		set("avg_days_in_inventory", avgDaysInInventory);
	}

	/**
	 * 均值-存货周转天数(天)
	 */
	public java.lang.Double getAvgDaysInInventory() {
		return get("avg_days_in_inventory");
	}

	/**
	 * 均值-带息债务／全部投入资本(%)
	 */
	public void setAvgInterestLiabOnCapital(java.lang.Double avgInterestLiabOnCapital) {
		set("avg_interest_liab_on_capital", avgInterestLiabOnCapital);
	}

	/**
	 * 均值-带息债务／全部投入资本(%)
	 */
	public java.lang.Double getAvgInterestLiabOnCapital() {
		return get("avg_interest_liab_on_capital");
	}

	/**
	 * 均值-流动资产／总资产(%)
	 */
	public void setAvgCurrentAssetRatio(java.lang.Double avgCurrentAssetRatio) {
		set("avg_current_asset_ratio", avgCurrentAssetRatio);
	}

	/**
	 * 均值-流动资产／总资产(%)
	 */
	public java.lang.Double getAvgCurrentAssetRatio() {
		return get("avg_current_asset_ratio");
	}

	/**
	 * 均值-有形资产／总资产(%)
	 */
	public void setAvgTangibleAssetRatio(java.lang.Double avgTangibleAssetRatio) {
		set("avg_tangible_asset_ratio", avgTangibleAssetRatio);
	}

	/**
	 * 均值-有形资产／总资产(%)
	 */
	public java.lang.Double getAvgTangibleAssetRatio() {
		return get("avg_tangible_asset_ratio");
	}

	/**
	 * 均值-总资产报酬率(%)
	 */
	public void setAvgRoa(java.lang.Double avgRoa) {
		set("avg_roa", avgRoa);
	}

	/**
	 * 均值-总资产报酬率(%)
	 */
	public java.lang.Double getAvgRoa() {
		return get("avg_roa");
	}

	/**
	 * 均值-非流动资产／总资产(%)
	 */
	public void setAvgNonCurrentAssetRatio(java.lang.Double avgNonCurrentAssetRatio) {
		set("avg_non_current_asset_ratio", avgNonCurrentAssetRatio);
	}

	/**
	 * 均值-非流动资产／总资产(%)
	 */
	public java.lang.Double getAvgNonCurrentAssetRatio() {
		return get("avg_non_current_asset_ratio");
	}

	/**
	 * 均值-有形资产／负债合计(%)
	 */
	public void setAvgTangibleAssetOnLiab(java.lang.Double avgTangibleAssetOnLiab) {
		set("avg_tangible_asset_on_liab", avgTangibleAssetOnLiab);
	}

	/**
	 * 均值-有形资产／负债合计(%)
	 */
	public java.lang.Double getAvgTangibleAssetOnLiab() {
		return get("avg_tangible_asset_on_liab");
	}

	/**
	 * 均值-流动负债／负债合计(%)
	 */
	public void setAvgCurrentLiabRatio(java.lang.Double avgCurrentLiabRatio) {
		set("avg_current_liab_ratio", avgCurrentLiabRatio);
	}

	/**
	 * 均值-流动负债／负债合计(%)
	 */
	public java.lang.Double getAvgCurrentLiabRatio() {
		return get("avg_current_liab_ratio");
	}

	/**
	 * 均值-销售毛利率(%)
	 */
	public void setAvgGrossProfitMargin(java.lang.Double avgGrossProfitMargin) {
		set("avg_gross_profit_margin", avgGrossProfitMargin);
	}

	/**
	 * 均值-销售毛利率(%)
	 */
	public java.lang.Double getAvgGrossProfitMargin() {
		return get("avg_gross_profit_margin");
	}

	/**
	 * 均值-营业总成本／营业总收入(%)
	 */
	public void setAvgOptCostOnIncome(java.lang.Double avgOptCostOnIncome) {
		set("avg_opt_cost_on_income", avgOptCostOnIncome);
	}

	/**
	 * 均值-营业总成本／营业总收入(%)
	 */
	public java.lang.Double getAvgOptCostOnIncome() {
		return get("avg_opt_cost_on_income");
	}

	/**
	 * 均值-投入资本回报率(%)
	 */
	public void setAvgRoic(java.lang.Double avgRoic) {
		set("avg_roic", avgRoic);
	}

	/**
	 * 均值-投入资本回报率(%)
	 */
	public java.lang.Double getAvgRoic() {
		return get("avg_roic");
	}

	/**
	 * 均值-营业收入-同比增长(%)
	 */
	public void setAvgOptIncomeGrowth(java.lang.Double avgOptIncomeGrowth) {
		set("avg_opt_income_growth", avgOptIncomeGrowth);
	}

	/**
	 * 均值-营业收入-同比增长(%)
	 */
	public java.lang.Double getAvgOptIncomeGrowth() {
		return get("avg_opt_income_growth");
	}

	/**
	 * 均值-净资产收益率-年化(%)
	 */
	public void setAvgRoe(java.lang.Double avgRoe) {
		set("avg_roe", avgRoe);
	}

	/**
	 * 均值-净资产收益率-年化(%)
	 */
	public java.lang.Double getAvgRoe() {
		return get("avg_roe");
	}

	/**
	 * 标准差-控股股东持股比例
	 */
	public void setStdTop1Hold(java.lang.Double stdTop1Hold) {
		set("std_top1_hold", stdTop1Hold);
	}

	/**
	 * 标准差-控股股东持股比例
	 */
	public java.lang.Double getStdTop1Hold() {
		return get("std_top1_hold");
	}

	/**
	 * 标准差-十大股东持股比例
	 */
	public void setStdTop10Hold(java.lang.Double stdTop10Hold) {
		set("std_top10_hold", stdTop10Hold);
	}

	/**
	 * 标准差-十大股东持股比例
	 */
	public java.lang.Double getStdTop10Hold() {
		return get("std_top10_hold");
	}

	/**
	 * 标准差-股权集中度
	 */
	public void setStdShareConc(java.lang.Double stdShareConc) {
		set("std_share_conc", stdShareConc);
	}

	/**
	 * 标准差-股权集中度
	 */
	public java.lang.Double getStdShareConc() {
		return get("std_share_conc");
	}

	/**
	 * 标准差-股权制衡度
	 */
	public void setStdShareBalance(java.lang.Double stdShareBalance) {
		set("std_share_balance", stdShareBalance);
	}

	/**
	 * 标准差-股权制衡度
	 */
	public java.lang.Double getStdShareBalance() {
		return get("std_share_balance");
	}

	/**
	 * 标准差-个人十大股东持股比例
	 */
	public void setStdPersonHold(java.lang.Double stdPersonHold) {
		set("std_person_hold", stdPersonHold);
	}

	/**
	 * 标准差-个人十大股东持股比例
	 */
	public java.lang.Double getStdPersonHold() {
		return get("std_person_hold");
	}

	/**
	 * 标准差-CEO学历 1-博士 2-硕士 3-本科 4-专科 0-其它
	 */
	public void setStdCeoEducation(java.lang.Long stdCeoEducation) {
		set("std_ceo_education", stdCeoEducation);
	}

	/**
	 * 标准差-CEO学历 1-博士 2-硕士 3-本科 4-专科 0-其它
	 */
	public java.lang.Long getStdCeoEducation() {
		return get("std_ceo_education");
	}

	/**
	 * 标准差-CEO年龄
	 */
	public void setStdCeoAge(java.lang.Long stdCeoAge) {
		set("std_ceo_age", stdCeoAge);
	}

	/**
	 * 标准差-CEO年龄
	 */
	public java.lang.Long getStdCeoAge() {
		return get("std_ceo_age");
	}

	/**
	 * 标准差-市盈率
	 */
	public void setStdPe(java.lang.Double stdPe) {
		set("std_pe", stdPe);
	}

	/**
	 * 标准差-市盈率
	 */
	public java.lang.Double getStdPe() {
		return get("std_pe");
	}

	/**
	 * 标准差-市净率
	 */
	public void setStdPb(java.lang.Double stdPb) {
		set("std_pb", stdPb);
	}

	/**
	 * 标准差-市净率
	 */
	public java.lang.Double getStdPb() {
		return get("std_pb");
	}

	/**
	 * 标准差-市销率
	 */
	public void setStdPs(java.lang.Double stdPs) {
		set("std_ps", stdPs);
	}

	/**
	 * 标准差-市销率
	 */
	public java.lang.Double getStdPs() {
		return get("std_ps");
	}

	/**
	 * 标准差-总股本（万股）
	 */
	public void setStdTotalStock(java.lang.Double stdTotalStock) {
		set("std_total_stock", stdTotalStock);
	}

	/**
	 * 标准差-总股本（万股）
	 */
	public java.lang.Double getStdTotalStock() {
		return get("std_total_stock");
	}

	/**
	 * 标准差-市值（亿元）
	 */
	public void setStdMarketCap(java.lang.Double stdMarketCap) {
		set("std_market_cap", stdMarketCap);
	}

	/**
	 * 标准差-市值（亿元）
	 */
	public java.lang.Double getStdMarketCap() {
		return get("std_market_cap");
	}

	/**
	 * 标准差-净利润(元)
	 */
	public void setStdNetProfit(java.lang.Double stdNetProfit) {
		set("std_net_profit", stdNetProfit);
	}

	/**
	 * 标准差-净利润(元)
	 */
	public java.lang.Double getStdNetProfit() {
		return get("std_net_profit");
	}

	/**
	 * 标准差-营业利润-同比增长(%)
	 */
	public void setStdOptProfitGrowth(java.lang.Double stdOptProfitGrowth) {
		set("std_opt_profit_growth", stdOptProfitGrowth);
	}

	/**
	 * 标准差-营业利润-同比增长(%)
	 */
	public java.lang.Double getStdOptProfitGrowth() {
		return get("std_opt_profit_growth");
	}

	/**
	 * 标准差-总资产净利率(%)
	 */
	public void setStdNetProfitOnAsset(java.lang.Double stdNetProfitOnAsset) {
		set("std_net_profit_on_asset", stdNetProfitOnAsset);
	}

	/**
	 * 标准差-总资产净利率(%)
	 */
	public java.lang.Double getStdNetProfitOnAsset() {
		return get("std_net_profit_on_asset");
	}

	/**
	 * 标准差-营业利润(元)
	 */
	public void setStdOptProfit(java.lang.Double stdOptProfit) {
		set("std_opt_profit", stdOptProfit);
	}

	/**
	 * 标准差-营业利润(元)
	 */
	public java.lang.Double getStdOptProfit() {
		return get("std_opt_profit");
	}

	/**
	 * 标准差-资产总计(元)
	 */
	public void setStdTotalAsset(java.lang.Double stdTotalAsset) {
		set("std_total_asset", stdTotalAsset);
	}

	/**
	 * 标准差-资产总计(元)
	 */
	public java.lang.Double getStdTotalAsset() {
		return get("std_total_asset");
	}

	/**
	 * 标准差-利润总额(元)
	 */
	public void setStdProfit(java.lang.Double stdProfit) {
		set("std_profit", stdProfit);
	}

	/**
	 * 标准差-利润总额(元)
	 */
	public java.lang.Double getStdProfit() {
		return get("std_profit");
	}

	/**
	 * 标准差-利润总额-同比增长(%)
	 */
	public void setStdProfitGrowth(java.lang.Double stdProfitGrowth) {
		set("std_profit_growth", stdProfitGrowth);
	}

	/**
	 * 标准差-利润总额-同比增长(%)
	 */
	public java.lang.Double getStdProfitGrowth() {
		return get("std_profit_growth");
	}

	/**
	 * 标准差-资产总计-相对年初增长(%)
	 */
	public void setStdTotalAssetGrowth(java.lang.Double stdTotalAssetGrowth) {
		set("std_total_asset_growth", stdTotalAssetGrowth);
	}

	/**
	 * 标准差-资产总计-相对年初增长(%)
	 */
	public java.lang.Double getStdTotalAssetGrowth() {
		return get("std_total_asset_growth");
	}

	/**
	 * 标准差-归属母公司股东的权益／负债合计(%)
	 */
	public void setStdHolderEquityOnLiab(java.lang.Double stdHolderEquityOnLiab) {
		set("std_holder_equity_on_liab", stdHolderEquityOnLiab);
	}

	/**
	 * 标准差-归属母公司股东的权益／负债合计(%)
	 */
	public java.lang.Double getStdHolderEquityOnLiab() {
		return get("std_holder_equity_on_liab");
	}

	/**
	 * 标准差-资产负债率(%)
	 */
	public void setStdLiabRatio(java.lang.Double stdLiabRatio) {
		set("std_liab_ratio", stdLiabRatio);
	}

	/**
	 * 标准差-资产负债率(%)
	 */
	public java.lang.Double getStdLiabRatio() {
		return get("std_liab_ratio");
	}

	/**
	 * 标准差-营业收入(元)
	 */
	public void setStdOptIncome(java.lang.Double stdOptIncome) {
		set("std_opt_income", stdOptIncome);
	}

	/**
	 * 标准差-营业收入(元)
	 */
	public java.lang.Double getStdOptIncome() {
		return get("std_opt_income");
	}

	/**
	 * 标准差-总资产周转率(次)
	 */
	public void setStdAssetTurnover(java.lang.Double stdAssetTurnover) {
		set("std_asset_turnover", stdAssetTurnover);
	}

	/**
	 * 标准差-总资产周转率(次)
	 */
	public java.lang.Double getStdAssetTurnover() {
		return get("std_asset_turnover");
	}

	/**
	 * 标准差-净利润／营业总收入(%)
	 */
	public void setStdNetProfitOnIncome(java.lang.Double stdNetProfitOnIncome) {
		set("std_net_profit_on_income", stdNetProfitOnIncome);
	}

	/**
	 * 标准差-净利润／营业总收入(%)
	 */
	public java.lang.Double getStdNetProfitOnIncome() {
		return get("std_net_profit_on_income");
	}

	/**
	 * 标准差-营业利润／营业总收入(%)
	 */
	public void setStdOptProfitOnIncome(java.lang.Double stdOptProfitOnIncome) {
		set("std_opt_profit_on_income", stdOptProfitOnIncome);
	}

	/**
	 * 标准差-营业利润／营业总收入(%)
	 */
	public java.lang.Double getStdOptProfitOnIncome() {
		return get("std_opt_profit_on_income");
	}

	/**
	 * 标准差-销售净利率(%)
	 */
	public void setStdNetProfitMargin(java.lang.Double stdNetProfitMargin) {
		set("std_net_profit_margin", stdNetProfitMargin);
	}

	/**
	 * 标准差-销售净利率(%)
	 */
	public java.lang.Double getStdNetProfitMargin() {
		return get("std_net_profit_margin");
	}

	/**
	 * 标准差-管理费用／营业总收入(%)
	 */
	public void setStdMaFeeOnIncome(java.lang.Double stdMaFeeOnIncome) {
		set("std_ma_fee_on_income", stdMaFeeOnIncome);
	}

	/**
	 * 标准差-管理费用／营业总收入(%)
	 */
	public java.lang.Double getStdMaFeeOnIncome() {
		return get("std_ma_fee_on_income");
	}

	/**
	 * 标准差-营业周期(天)
	 */
	public void setStdTradeCycle(java.lang.Double stdTradeCycle) {
		set("std_trade_cycle", stdTradeCycle);
	}

	/**
	 * 标准差-营业周期(天)
	 */
	public java.lang.Double getStdTradeCycle() {
		return get("std_trade_cycle");
	}

	/**
	 * 标准差-存货周转天数(天)
	 */
	public void setStdDaysInInventory(java.lang.Double stdDaysInInventory) {
		set("std_days_in_inventory", stdDaysInInventory);
	}

	/**
	 * 标准差-存货周转天数(天)
	 */
	public java.lang.Double getStdDaysInInventory() {
		return get("std_days_in_inventory");
	}

	/**
	 * 标准差-带息债务／全部投入资本(%)
	 */
	public void setStdInterestLiabOnCapital(java.lang.Double stdInterestLiabOnCapital) {
		set("std_interest_liab_on_capital", stdInterestLiabOnCapital);
	}

	/**
	 * 标准差-带息债务／全部投入资本(%)
	 */
	public java.lang.Double getStdInterestLiabOnCapital() {
		return get("std_interest_liab_on_capital");
	}

	/**
	 * 标准差-流动资产／总资产(%)
	 */
	public void setStdCurrentAssetRatio(java.lang.Double stdCurrentAssetRatio) {
		set("std_current_asset_ratio", stdCurrentAssetRatio);
	}

	/**
	 * 标准差-流动资产／总资产(%)
	 */
	public java.lang.Double getStdCurrentAssetRatio() {
		return get("std_current_asset_ratio");
	}

	/**
	 * 标准差-有形资产／总资产(%)
	 */
	public void setStdTangibleAssetRatio(java.lang.Double stdTangibleAssetRatio) {
		set("std_tangible_asset_ratio", stdTangibleAssetRatio);
	}

	/**
	 * 标准差-有形资产／总资产(%)
	 */
	public java.lang.Double getStdTangibleAssetRatio() {
		return get("std_tangible_asset_ratio");
	}

	/**
	 * 标准差-总资产报酬率(%)
	 */
	public void setStdRoa(java.lang.Double stdRoa) {
		set("std_roa", stdRoa);
	}

	/**
	 * 标准差-总资产报酬率(%)
	 */
	public java.lang.Double getStdRoa() {
		return get("std_roa");
	}

	/**
	 * 标准差-非流动资产／总资产(%)
	 */
	public void setStdNonCurrentAssetRatio(java.lang.Double stdNonCurrentAssetRatio) {
		set("std_non_current_asset_ratio", stdNonCurrentAssetRatio);
	}

	/**
	 * 标准差-非流动资产／总资产(%)
	 */
	public java.lang.Double getStdNonCurrentAssetRatio() {
		return get("std_non_current_asset_ratio");
	}

	/**
	 * 标准差-有形资产／负债合计(%)
	 */
	public void setStdTangibleAssetOnLiab(java.lang.Double stdTangibleAssetOnLiab) {
		set("std_tangible_asset_on_liab", stdTangibleAssetOnLiab);
	}

	/**
	 * 标准差-有形资产／负债合计(%)
	 */
	public java.lang.Double getStdTangibleAssetOnLiab() {
		return get("std_tangible_asset_on_liab");
	}

	/**
	 * 标准差-流动负债／负债合计(%)
	 */
	public void setStdCurrentLiabRatio(java.lang.Double stdCurrentLiabRatio) {
		set("std_current_liab_ratio", stdCurrentLiabRatio);
	}

	/**
	 * 标准差-流动负债／负债合计(%)
	 */
	public java.lang.Double getStdCurrentLiabRatio() {
		return get("std_current_liab_ratio");
	}

	/**
	 * 标准差-销售毛利率(%)
	 */
	public void setStdGrossProfitMargin(java.lang.Double stdGrossProfitMargin) {
		set("std_gross_profit_margin", stdGrossProfitMargin);
	}

	/**
	 * 标准差-销售毛利率(%)
	 */
	public java.lang.Double getStdGrossProfitMargin() {
		return get("std_gross_profit_margin");
	}

	/**
	 * 标准差-营业总成本／营业总收入(%)
	 */
	public void setStdOptCostOnIncome(java.lang.Double stdOptCostOnIncome) {
		set("std_opt_cost_on_income", stdOptCostOnIncome);
	}

	/**
	 * 标准差-营业总成本／营业总收入(%)
	 */
	public java.lang.Double getStdOptCostOnIncome() {
		return get("std_opt_cost_on_income");
	}

	/**
	 * 标准差-投入资本回报率(%)
	 */
	public void setStdRoic(java.lang.Double stdRoic) {
		set("std_roic", stdRoic);
	}

	/**
	 * 标准差-投入资本回报率(%)
	 */
	public java.lang.Double getStdRoic() {
		return get("std_roic");
	}

	/**
	 * 标准差-营业收入-同比增长(%)
	 */
	public void setStdOptIncomeGrowth(java.lang.Double stdOptIncomeGrowth) {
		set("std_opt_income_growth", stdOptIncomeGrowth);
	}

	/**
	 * 标准差-营业收入-同比增长(%)
	 */
	public java.lang.Double getStdOptIncomeGrowth() {
		return get("std_opt_income_growth");
	}

	/**
	 * 标准差-净资产收益率-年化(%)
	 */
	public void setStdRoe(java.lang.Double stdRoe) {
		set("std_roe", stdRoe);
	}

	/**
	 * 标准差-净资产收益率-年化(%)
	 */
	public java.lang.Double getStdRoe() {
		return get("std_roe");
	}

}
