package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmOrgExtendEntity<M extends BasePmOrgExtendEntity<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "pm_org_extend_entity";

	/**
	 * 机构ID
	 */
	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	/**
	 * 机构ID
	 */
	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

	/**
	 * 机构中文简称
	 */
	public void setOrgCnShort(java.lang.String orgCnShort) {
		set("org_cn_short", orgCnShort);
	}

	/**
	 * 机构中文简称
	 */
	public java.lang.String getOrgCnShort() {
		return get("org_cn_short");
	}

	/**
	 * 机构对应的主要逻辑实体
	 */
	public void setOrgPrimeEntity(java.lang.String orgPrimeEntity) {
		set("org_prime_entity", orgPrimeEntity);
	}

	/**
	 * 机构对应的主要逻辑实体
	 */
	public java.lang.String getOrgPrimeEntity() {
		return get("org_prime_entity");
	}

	/**
	 * 机构疑似关联实体
	 */
	public void setOrgEntity(java.lang.String orgEntity) {
		set("org_entity", orgEntity);
	}

	/**
	 * 机构疑似关联实体
	 */
	public java.lang.String getOrgEntity() {
		return get("org_entity");
	}

	/**
	 * 机构实体的UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 机构实体的UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

}
