package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntIndustry<M extends BaseEntIndustry<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_industry";

	/**
	 * 股票代码
	 */
	public void setStockCode(java.lang.String stockCode) {
		set("stock_code", stockCode);
	}

	/**
	 * 股票代码
	 */
	public java.lang.String getStockCode() {
		return get("stock_code");
	}

	/**
	 * 证监会行业
	 */
	public void setCsrcIndustry(java.lang.String csrcIndustry) {
		set("csrc_industry", csrcIndustry);
	}

	/**
	 * 证监会行业
	 */
	public java.lang.String getCsrcIndustry() {
		return get("csrc_industry");
	}

	/**
	 * 证监会行业代码
	 */
	public void setCsrcCode(java.lang.String csrcCode) {
		set("csrc_code", csrcCode);
	}

	/**
	 * 证监会行业代码
	 */
	public java.lang.String getCsrcCode() {
		return get("csrc_code");
	}

	/**
	 * 申万行业
	 */
	public void setSwIndustry(java.lang.String swIndustry) {
		set("sw_industry", swIndustry);
	}

	/**
	 * 申万行业
	 */
	public java.lang.String getSwIndustry() {
		return get("sw_industry");
	}

	/**
	 * 申万行业代码
	 */
	public void setSwCode(java.lang.String swCode) {
		set("sw_code", swCode);
	}

	/**
	 * 申万行业代码
	 */
	public java.lang.String getSwCode() {
		return get("sw_code");
	}

	/**
	 * 东财行业
	 */
	public void setEmIndustry(java.lang.String emIndustry) {
		set("em_industry", emIndustry);
	}

	/**
	 * 东财行业
	 */
	public java.lang.String getEmIndustry() {
		return get("em_industry");
	}

	/**
	 * 东财行业代码
	 */
	public void setEmCode(java.lang.String emCode) {
		set("em_code", emCode);
	}

	/**
	 * 东财行业代码
	 */
	public java.lang.String getEmCode() {
		return get("em_code");
	}

	/**
	 * 新三板管理型行业
	 */
	public void setXsbManageIndustry(java.lang.String xsbManageIndustry) {
		set("xsb_manage_industry", xsbManageIndustry);
	}

	/**
	 * 新三板管理型行业
	 */
	public java.lang.String getXsbManageIndustry() {
		return get("xsb_manage_industry");
	}

	/**
	 * 新三板管理型行业代码
	 */
	public void setXsbManageCode(java.lang.String xsbManageCode) {
		set("xsb_manage_code", xsbManageCode);
	}

	/**
	 * 新三板管理型行业代码
	 */
	public java.lang.String getXsbManageCode() {
		return get("xsb_manage_code");
	}

	/**
	 * 新三板投资型行业
	 */
	public void setXsbInvestIndustry(java.lang.String xsbInvestIndustry) {
		set("xsb_invest_industry", xsbInvestIndustry);
	}

	/**
	 * 新三板投资型行业
	 */
	public java.lang.String getXsbInvestIndustry() {
		return get("xsb_invest_industry");
	}

	/**
	 * 新三板投资型行业代码
	 */
	public void setXsbInvestCode(java.lang.String xsbInvestCode) {
		set("xsb_invest_code", xsbInvestCode);
	}

	/**
	 * 新三板投资型行业代码
	 */
	public java.lang.String getXsbInvestCode() {
		return get("xsb_invest_code");
	}

}
