package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRptToeMa<M extends BaseRptToeMa<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rpt_toe_ma";

	/**
	 * 自增Id
	 */
	public void setMaId(java.lang.Integer maId) {
		set("ma_id", maId);
	}

	/**
	 * 自增Id
	 */
	public java.lang.Integer getMaId() {
		return get("ma_id");
	}

	/**
	 * 上市公司代码
	 */
	public void setToeCode(java.lang.String toeCode) {
		set("toe_code", toeCode);
	}

	/**
	 * 上市公司代码
	 */
	public java.lang.String getToeCode() {
		return get("toe_code");
	}

	/**
	 * 上市公司简称
	 */
	public void setToeName(java.lang.String toeName) {
		set("toe_name", toeName);
	}

	/**
	 * 上市公司简称
	 */
	public java.lang.String getToeName() {
		return get("toe_name");
	}

	/**
	 * 上市公司UUID
	 */
	public void setToeUuid(java.lang.String toeUuid) {
		set("toe_uuid", toeUuid);
	}

	/**
	 * 上市公司UUID
	 */
	public java.lang.String getToeUuid() {
		return get("toe_uuid");
	}

	/**
	 * 最新公告日期
	 */
	public void setHappenDate(java.lang.String happenDate) {
		set("happen_date", happenDate);
	}

	/**
	 * 最新公告日期
	 */
	public java.lang.String getHappenDate() {
		return get("happen_date");
	}

	/**
	 * 首次公告日期
	 */
	public void setStartDate(java.lang.String startDate) {
		set("start_date", startDate);
	}

	/**
	 * 首次公告日期
	 */
	public java.lang.String getStartDate() {
		return get("start_date");
	}

	/**
	 * 最新进度
	 */
	public void setTips(java.lang.String tips) {
		set("tips", tips);
	}

	/**
	 * 最新进度
	 */
	public java.lang.String getTips() {
		return get("tips");
	}

	/**
	 * 交易简介
	 */
	public void setAbst(java.lang.String abst) {
		set("abst", abst);
	}

	/**
	 * 交易简介
	 */
	public java.lang.String getAbst() {
		return get("abst");
	}

	/**
	 * 标的-公司名称
	 */
	public void setTargetName(java.lang.String targetName) {
		set("target_name", targetName);
	}

	/**
	 * 标的-公司名称
	 */
	public java.lang.String getTargetName() {
		return get("target_name");
	}

	/**
	 * 标的企业UUID
	 */
	public void setTargetUuid(java.lang.String targetUuid) {
		set("target_uuid", targetUuid);
	}

	/**
	 * 标的企业UUID
	 */
	public java.lang.String getTargetUuid() {
		return get("target_uuid");
	}

	/**
	 * 标的-与披露方关系
	 */
	public void setTargetRelation(java.lang.String targetRelation) {
		set("target_relation", targetRelation);
	}

	/**
	 * 标的-与披露方关系
	 */
	public java.lang.String getTargetRelation() {
		return get("target_relation");
	}

	/**
	 * 标的-所属行业
	 */
	public void setTargetIndustry(java.lang.String targetIndustry) {
		set("target_industry", targetIndustry);
	}

	/**
	 * 标的-所属行业
	 */
	public java.lang.String getTargetIndustry() {
		return get("target_industry");
	}

	/**
	 * 买方-企业名称
	 */
	public void setBuyerName(java.lang.String buyerName) {
		set("buyer_name", buyerName);
	}

	/**
	 * 买方-企业名称
	 */
	public java.lang.String getBuyerName() {
		return get("buyer_name");
	}

	/**
	 * 买方企业UUID
	 */
	public void setBuyerToeUuid(java.lang.String buyerToeUuid) {
		set("buyer_toe_uuid", buyerToeUuid);
	}

	/**
	 * 买方企业UUID
	 */
	public java.lang.String getBuyerToeUuid() {
		return get("buyer_toe_uuid");
	}

	/**
	 * 买方-企业证券代码
	 */
	public void setBuyerToeCode(java.lang.String buyerToeCode) {
		set("buyer_toe_code", buyerToeCode);
	}

	/**
	 * 买方-企业证券代码
	 */
	public java.lang.String getBuyerToeCode() {
		return get("buyer_toe_code");
	}

	/**
	 * 买方-企业性质
	 */
	public void setBuyerType(java.lang.String buyerType) {
		set("buyer_type", buyerType);
	}

	/**
	 * 买方-企业性质
	 */
	public java.lang.String getBuyerType() {
		return get("buyer_type");
	}

	/**
	 * 买方-与披露方关系
	 */
	public void setBuyerRelation(java.lang.String buyerRelation) {
		set("buyer_relation", buyerRelation);
	}

	/**
	 * 买方-与披露方关系
	 */
	public java.lang.String getBuyerRelation() {
		return get("buyer_relation");
	}

	/**
	 * 买方-所属行业
	 */
	public void setBuyerIndustry(java.lang.String buyerIndustry) {
		set("buyer_industry", buyerIndustry);
	}

	/**
	 * 买方-所属行业
	 */
	public java.lang.String getBuyerIndustry() {
		return get("buyer_industry");
	}

	/**
	 * 买方-受让以后持股数（万股）
	 */
	public void setBuyerStockNum(java.lang.Double buyerStockNum) {
		set("buyer_stock_num", buyerStockNum);
	}

	/**
	 * 买方-受让以后持股数（万股）
	 */
	public java.lang.Double getBuyerStockNum() {
		return get("buyer_stock_num");
	}

	/**
	 * 买方-受让以后持股比例（%）
	 */
	public void setBuyerStockRate(java.lang.Double buyerStockRate) {
		set("buyer_stock_rate", buyerStockRate);
	}

	/**
	 * 买方-受让以后持股比例（%）
	 */
	public java.lang.Double getBuyerStockRate() {
		return get("buyer_stock_rate");
	}

	/**
	 * 卖方-企业名称
	 */
	public void setOwnerName(java.lang.String ownerName) {
		set("owner_name", ownerName);
	}

	/**
	 * 卖方-企业名称
	 */
	public java.lang.String getOwnerName() {
		return get("owner_name");
	}

	/**
	 * 卖方-企业证券代码卖方企业UUID
	 */
	public void setOwnerToeUuid(java.lang.String ownerToeUuid) {
		set("owner_toe_uuid", ownerToeUuid);
	}

	/**
	 * 卖方-企业证券代码卖方企业UUID
	 */
	public java.lang.String getOwnerToeUuid() {
		return get("owner_toe_uuid");
	}

	/**
	 * 卖方-企业证券代码
	 */
	public void setOwnerToeCode(java.lang.String ownerToeCode) {
		set("owner_toe_code", ownerToeCode);
	}

	/**
	 * 卖方-企业证券代码
	 */
	public java.lang.String getOwnerToeCode() {
		return get("owner_toe_code");
	}

	/**
	 * 卖方-企业性质
	 */
	public void setOwnerType(java.lang.String ownerType) {
		set("owner_type", ownerType);
	}

	/**
	 * 卖方-企业性质
	 */
	public java.lang.String getOwnerType() {
		return get("owner_type");
	}

	/**
	 * 卖方-与披露方关系
	 */
	public void setOwnerRelation(java.lang.String ownerRelation) {
		set("owner_relation", ownerRelation);
	}

	/**
	 * 卖方-与披露方关系
	 */
	public java.lang.String getOwnerRelation() {
		return get("owner_relation");
	}

	/**
	 * 卖方-所属行业
	 */
	public void setOwnerIndustry(java.lang.String ownerIndustry) {
		set("owner_industry", ownerIndustry);
	}

	/**
	 * 卖方-所属行业
	 */
	public java.lang.String getOwnerIndustry() {
		return get("owner_industry");
	}

	/**
	 * 卖方-受让以后持股数（万股）
	 */
	public void setOwnerStockNum(java.lang.Double ownerStockNum) {
		set("owner_stock_num", ownerStockNum);
	}

	/**
	 * 卖方-受让以后持股数（万股）
	 */
	public java.lang.Double getOwnerStockNum() {
		return get("owner_stock_num");
	}

	/**
	 * 卖方-受让以后持股比例（%）
	 */
	public void setOwnerStockRate(java.lang.Double ownerStockRate) {
		set("owner_stock_rate", ownerStockRate);
	}

	/**
	 * 卖方-受让以后持股比例（%）
	 */
	public java.lang.Double getOwnerStockRate() {
		return get("owner_stock_rate");
	}

	/**
	 * 并购目的
	 */
	public void setMaSeason(java.lang.String maSeason) {
		set("ma_season", maSeason);
	}

	/**
	 * 并购目的
	 */
	public java.lang.String getMaSeason() {
		return get("ma_season");
	}

	/**
	 * 并购方式
	 */
	public void setMaType(java.lang.String maType) {
		set("ma_type", maType);
	}

	/**
	 * 并购方式
	 */
	public java.lang.String getMaType() {
		return get("ma_type");
	}

	/**
	 * 支付方式
	 */
	public void setPayMode(java.lang.String payMode) {
		set("pay_mode", payMode);
	}

	/**
	 * 支付方式
	 */
	public java.lang.String getPayMode() {
		return get("pay_mode");
	}

	/**
	 * 交易金额（万元）
	 */
	public void setPay(java.lang.Double pay) {
		set("pay", pay);
	}

	/**
	 * 交易金额（万元）
	 */
	public java.lang.Double getPay() {
		return get("pay");
	}

	/**
	 * 支付金额的币种
	 */
	public void setPayKind(java.lang.String payKind) {
		set("pay_kind", payKind);
	}

	/**
	 * 支付金额的币种
	 */
	public java.lang.String getPayKind() {
		return get("pay_kind");
	}

	/**
	 * 转让价格（元）
	 */
	public void setTransPrice(java.lang.Double transPrice) {
		set("trans_price", transPrice);
	}

	/**
	 * 转让价格（元）
	 */
	public java.lang.Double getTransPrice() {
		return get("trans_price");
	}

	/**
	 * 转让价格的币种
	 */
	public void setTransKind(java.lang.String transKind) {
		set("trans_kind", transKind);
	}

	/**
	 * 转让价格的币种
	 */
	public java.lang.String getTransKind() {
		return get("trans_kind");
	}

	/**
	 * 标的类型
	 */
	public void setTargetType(java.lang.String targetType) {
		set("target_type", targetType);
	}

	/**
	 * 标的类型
	 */
	public java.lang.String getTargetType() {
		return get("target_type");
	}

	/**
	 * 股权转让比例（%）
	 */
	public void setTransStockRate(java.lang.Double transStockRate) {
		set("trans_stock_rate", transStockRate);
	}

	/**
	 * 股权转让比例（%）
	 */
	public java.lang.Double getTransStockRate() {
		return get("trans_stock_rate");
	}

	/**
	 * 控制权是否变更
	 */
	public void setIfChanged(java.lang.String ifChanged) {
		set("if_changed", ifChanged);
	}

	/**
	 * 控制权是否变更
	 */
	public java.lang.String getIfChanged() {
		return get("if_changed");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
