package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntBranch<M extends BaseEntBranch<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_branch";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 分支企业UUID
	 */
	public void setBUuid(java.lang.String bUuid) {
		set("b_uuid", bUuid);
	}

	/**
	 * 分支企业UUID
	 */
	public java.lang.String getBUuid() {
		return get("b_uuid");
	}

	/**
	 * 分支企业名称
	 */
	public void setBName(java.lang.String bName) {
		set("b_name", bName);
	}

	/**
	 * 分支企业名称
	 */
	public java.lang.String getBName() {
		return get("b_name");
	}

	/**
	 * 分支企业法人
	 */
	public void setBLegal(java.lang.String bLegal) {
		set("b_legal", bLegal);
	}

	/**
	 * 分支企业法人
	 */
	public java.lang.String getBLegal() {
		return get("b_legal");
	}

}
