package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRdsEntPatent<M extends BaseRdsEntPatent<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rds_ent_patent";

	/**
	 * 企业编码
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业编码
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 企业专利信息（专利名称，类型， 授权公告号，申请号，摘要，授权公告日，申请日）
	 */
	public void setRecord(java.lang.String record) {
		set("record", record);
	}

	/**
	 * 企业专利信息（专利名称，类型， 授权公告号，申请号，摘要，授权公告日，申请日）
	 */
	public java.lang.String getRecord() {
		return get("record");
	}

}
