package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmIdOrgFund<M extends BasePmIdOrgFund<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "pm_id_org_fund";

	/**
	 * 机构ID
	 */
	public void setOrgId(java.lang.Integer orgId) {
		set("org_id", orgId);
	}

	/**
	 * 机构ID
	 */
	public java.lang.Integer getOrgId() {
		return get("org_id");
	}

	/**
	 * 基金ID
	 */
	public void setFundId(java.lang.Integer fundId) {
		set("fund_id", fundId);
	}

	/**
	 * 基金ID
	 */
	public java.lang.Integer getFundId() {
		return get("fund_id");
	}

}
