package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntCopyrights<M extends BaseEntCopyrights<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_copyrights";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 作品著作权名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 作品著作权名称
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 作品著作权登记号
	 */
	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	/**
	 * 作品著作权登记号
	 */
	public java.lang.String getNumber() {
		return get("number");
	}

	/**
	 * 登记日期
	 */
	public void setAppDate(java.lang.String appDate) {
		set("app_date", appDate);
	}

	/**
	 * 登记日期
	 */
	public java.lang.String getAppDate() {
		return get("app_date");
	}

	/**
	 * 著作权类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

	/**
	 * 著作权类型
	 */
	public java.lang.String getType() {
		return get("type");
	}

	/**
	 * 创作完成日期
	 */
	public void setFinDate(java.lang.String finDate) {
		set("fin_date", finDate);
	}

	/**
	 * 创作完成日期
	 */
	public java.lang.String getFinDate() {
		return get("fin_date");
	}

	/**
	 * 首次发布日期
	 */
	public void setPubDate(java.lang.String pubDate) {
		set("pub_date", pubDate);
	}

	/**
	 * 首次发布日期
	 */
	public java.lang.String getPubDate() {
		return get("pub_date");
	}

}
