package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppRumorInteraction<M extends BaseAppRumorInteraction<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "app_rumor_interaction";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * rumor ID
	 */
	public void setRumorId(java.lang.Integer rumorId) {
		set("rumor_id", rumorId);
	}

	/**
	 * rumor ID
	 */
	public java.lang.Integer getRumorId() {
		return get("rumor_id");
	}

	/**
	 * 评论人
	 */
	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	/**
	 * 评论人
	 */
	public java.lang.String getUserName() {
		return get("user_name");
	}

	/**
	 * 1--点赞，2--评论
	 */
	public void setMessageType(java.lang.Integer messageType) {
		set("message_type", messageType);
	}

	/**
	 * 1--点赞，2--评论
	 */
	public java.lang.Integer getMessageType() {
		return get("message_type");
	}

	/**
	 * 评论
	 */
	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	/**
	 * 评论
	 */
	public java.lang.String getMessage() {
		return get("message");
	}

	/**
	 * 
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
