package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockFinanceChartIndustry<M extends BaseStockFinanceChartIndustry<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_finance_chart_industry";

	/**
	 * 东财行业
	 */
	public void setEmIndustry(java.lang.String emIndustry) {
		set("em_industry", emIndustry);
	}

	/**
	 * 东财行业
	 */
	public java.lang.String getEmIndustry() {
		return get("em_industry");
	}

	/**
	 * 报告日期
	 */
	public void setReportDate(java.lang.String reportDate) {
		set("report_date", reportDate);
	}

	/**
	 * 报告日期
	 */
	public java.lang.String getReportDate() {
		return get("report_date");
	}

	/**
	 * 指标名称
	 */
	public void setFinanceItem(java.lang.String financeItem) {
		set("finance_item", financeItem);
	}

	/**
	 * 指标名称
	 */
	public java.lang.String getFinanceItem() {
		return get("finance_item");
	}

	/**
	 * 指标最大值
	 */
	public void setMaxValue(java.lang.Double maxValue) {
		set("max_value", maxValue);
	}

	/**
	 * 指标最大值
	 */
	public java.lang.Double getMaxValue() {
		return get("max_value");
	}

	/**
	 * 指标最小值
	 */
	public void setMinValue(java.lang.Double minValue) {
		set("min_value", minValue);
	}

	/**
	 * 指标最小值
	 */
	public java.lang.Double getMinValue() {
		return get("min_value");
	}

	/**
	 * 指标均值
	 */
	public void setAvgValue(java.lang.Double avgValue) {
		set("avg_value", avgValue);
	}

	/**
	 * 指标均值
	 */
	public java.lang.Double getAvgValue() {
		return get("avg_value");
	}

	/**
	 * 90分位数
	 */
	public void setPercentile90(java.lang.Double percentile90) {
		set("percentile_90", percentile90);
	}

	/**
	 * 90分位数
	 */
	public java.lang.Double getPercentile90() {
		return get("percentile_90");
	}

	/**
	 * 10分位数
	 */
	public void setPercentile10(java.lang.Double percentile10) {
		set("percentile_10", percentile10);
	}

	/**
	 * 10分位数
	 */
	public java.lang.Double getPercentile10() {
		return get("percentile_10");
	}

}
