package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePmFundInfo<M extends BasePmFundInfo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "pm_fund_info";

	/**
	 * 
	 */
	public void setFundId(java.lang.Integer fundId) {
		set("fund_id", fundId);
	}

	/**
	 * 
	 */
	public java.lang.Integer getFundId() {
		return get("fund_id");
	}

	/**
	 * 
	 */
	public void setFundName(java.lang.String fundName) {
		set("fund_name", fundName);
	}

	/**
	 * 
	 */
	public java.lang.String getFundName() {
		return get("fund_name");
	}

	/**
	 * 
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}

	/**
	 * 
	 */
	public java.lang.String getCity() {
		return get("city");
	}

	/**
	 * 
	 */
	public void setTown(java.lang.String town) {
		set("town", town);
	}

	/**
	 * 
	 */
	public java.lang.String getTown() {
		return get("town");
	}

	/**
	 * 
	 */
	public void setCollectFinishDate(java.lang.String collectFinishDate) {
		set("collect_finish_date", collectFinishDate);
	}

	/**
	 * 
	 */
	public java.lang.String getCollectFinishDate() {
		return get("collect_finish_date");
	}

	/**
	 * 
	 */
	public void setInvestDate(java.lang.String investDate) {
		set("invest_date", investDate);
	}

	/**
	 * 
	 */
	public java.lang.String getInvestDate() {
		return get("invest_date");
	}

	/**
	 * 
	 */
	public void setFundDesc(java.lang.String fundDesc) {
		set("fund_desc", fundDesc);
	}

	/**
	 * 
	 */
	public java.lang.String getFundDesc() {
		return get("fund_desc");
	}

}
