package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockEquityctrl<M extends BaseStockEquityctrl<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_equityctrl";

	/**
	 * 股票代码
	 */
	public void setStockCode(java.lang.String stockCode) {
		set("stock_code", stockCode);
	}

	/**
	 * 股票代码
	 */
	public java.lang.String getStockCode() {
		return get("stock_code");
	}

	/**
	 * 企业名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 子公司信息
	 */
	public void setEqComp(java.lang.String eqComp) {
		set("eq_comp", eqComp);
	}

	/**
	 * 子公司信息
	 */
	public java.lang.String getEqComp() {
		return get("eq_comp");
	}

}
