package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockInstInvest<M extends BaseStockInstInvest<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_inst_invest";

	/**
	 * 股票代码
	 */
	public void setStockCode(java.lang.String stockCode) {
		set("stock_code", stockCode);
	}

	/**
	 * 股票代码
	 */
	public java.lang.String getStockCode() {
		return get("stock_code");
	}

	/**
	 * 企业名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 企业名称
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 机构投资者
	 */
	public void setInstInv(java.lang.String instInv) {
		set("inst_inv", instInv);
	}

	/**
	 * 机构投资者
	 */
	public java.lang.String getInstInv() {
		return get("inst_inv");
	}

}
