package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockListPotentialMa<M extends BaseStockListPotentialMa<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_list_potential_ma";

	/**
	 * 上市公司股票代码
	 */
	public void setListStockCode(java.lang.String listStockCode) {
		set("list_stock_code", listStockCode);
	}

	/**
	 * 上市公司股票代码
	 */
	public java.lang.String getListStockCode() {
		return get("list_stock_code");
	}

	/**
	 * 潜在并购新三板标的
	 */
	public void setXsbStockCode(java.lang.String xsbStockCode) {
		set("xsb_stock_code", xsbStockCode);
	}

	/**
	 * 潜在并购新三板标的
	 */
	public java.lang.String getXsbStockCode() {
		return get("xsb_stock_code");
	}

	/**
	 * 是否选取为上市公司潜在并购标的
	 */
	public void setIsListMa(java.lang.Integer isListMa) {
		set("is_list_ma", isListMa);
	}

	/**
	 * 是否选取为上市公司潜在并购标的
	 */
	public java.lang.Integer getIsListMa() {
		return get("is_list_ma");
	}

	/**
	 * 是否选取为新三板潜在上市公司并购方
	 */
	public void setIsXsbMa(java.lang.Integer isXsbMa) {
		set("is_xsb_ma", isXsbMa);
	}

	/**
	 * 是否选取为新三板潜在上市公司并购方
	 */
	public java.lang.Integer getIsXsbMa() {
		return get("is_xsb_ma");
	}

}
