package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppRumorTopic<M extends BaseAppRumorTopic<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "app_rumor_topic";

	/**
	 * 自增id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增id
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 情报ID
	 */
	public void setRumorId(java.lang.Integer rumorId) {
		set("rumor_id", rumorId);
	}

	/**
	 * 情报ID
	 */
	public java.lang.Integer getRumorId() {
		return get("rumor_id");
	}

	/**
	 * topic_id
	 */
	public void setTopicId(java.lang.Integer topicId) {
		set("topic_id", topicId);
	}

	/**
	 * topic_id
	 */
	public java.lang.Integer getTopicId() {
		return get("topic_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
