package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockFinanceChart<M extends BaseStockFinanceChart<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stock_finance_chart";

	/**
	 * 股票代码
	 */
	public void setStockCode(java.lang.String stockCode) {
		set("stock_code", stockCode);
	}

	/**
	 * 股票代码
	 */
	public java.lang.String getStockCode() {
		return get("stock_code");
	}

	/**
	 * 报告日期
	 */
	public void setReportDate(java.lang.String reportDate) {
		set("report_date", reportDate);
	}

	/**
	 * 报告日期
	 */
	public java.lang.String getReportDate() {
		return get("report_date");
	}

	/**
	 * 指标名称
	 */
	public void setFinanceItem(java.lang.String financeItem) {
		set("finance_item", financeItem);
	}

	/**
	 * 指标名称
	 */
	public java.lang.String getFinanceItem() {
		return get("finance_item");
	}

	/**
	 * 指标数值
	 */
	public void setFinanceValue(java.lang.Double financeValue) {
		set("finance_value", financeValue);
	}

	/**
	 * 指标数值
	 */
	public java.lang.Double getFinanceValue() {
		return get("finance_value");
	}

	/**
	 * 东财行业
	 */
	public void setEmIndustry(java.lang.String emIndustry) {
		set("em_industry", emIndustry);
	}

	/**
	 * 东财行业
	 */
	public java.lang.String getEmIndustry() {
		return get("em_industry");
	}

}
