package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRdsEntInvest<M extends BaseRdsEntInvest<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rds_ent_invest";

	/**
	 * 企业编码
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业编码
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 企业对外投资信息（投资企业名称、投资企业UUID、投资企业成立时间、投资企业法定代表人）
	 */
	public void setRecord(java.lang.String record) {
		set("record", record);
	}

	/**
	 * 企业对外投资信息（投资企业名称、投资企业UUID、投资企业成立时间、投资企业法定代表人）
	 */
	public java.lang.String getRecord() {
		return get("record");
	}

}
