package com.kd.model.general;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("app_rumor_interaction", "id", AppRumorInteraction.class);
		arp.addMapping("app_rumor_topic", "id", AppRumorTopic.class);
		arp.addMapping("ent_abnormal_item", "id", EntAbnormalItem.class);
		arp.addMapping("ent_basic_info" , EntBasicInfo.class);
		arp.addMapping("ent_branch" , EntBranch.class);
		arp.addMapping("ent_chg_record" , EntChgRecord.class);
		arp.addMapping("ent_copyrights" , EntCopyrights.class);
		arp.addMapping("ent_equity" , EntEquity.class);
		arp.addMapping("ent_industry" , EntIndustry.class);
		arp.addMapping("ent_related" , EntRelated.class);
		arp.addMapping("ent_soft_copyrights" , EntSoftCopyrights.class);
		arp.addMapping("event_topic", "id", EventTopic.class);
		arp.addMapping("id_category", "biz_id", IdCategory.class);
		arp.addMapping("id_ent_stock" , IdEntStock.class);
		arp.addMapping("id_org_exit_event" , IdOrgExitEvent.class);
		arp.addMapping("id_person_exit_event" , IdPersonExitEvent.class);
		arp.addMapping("ops_category_media", "id", OpsCategoryMedia.class);
		arp.addMapping("ops_city_lnglat_info" , OpsCityLnglatInfo.class);
		arp.addMapping("pm_exit_event", "event_id", PmExitEvent.class);
		arp.addMapping("pm_exit_event_detail", "event_id", PmExitEventDetail.class);
		arp.addMapping("pm_fund_info", "fund_id", PmFundInfo.class);
		arp.addMapping("pm_id_fund_exit_event" , PmIdFundExitEvent.class);
		arp.addMapping("pm_id_fund_invest_event" , PmIdFundInvestEvent.class);
		arp.addMapping("pm_id_org_exit_event" , PmIdOrgExitEvent.class);
		arp.addMapping("pm_id_org_fund" , PmIdOrgFund.class);
		arp.addMapping("pm_id_org_invest_event" , PmIdOrgInvestEvent.class);
		arp.addMapping("pm_id_user_exit_event" , PmIdUserExitEvent.class);
		arp.addMapping("pm_id_user_invest_event" , PmIdUserInvestEvent.class);
		arp.addMapping("pm_invest_event", "event_id", PmInvestEvent.class);
		arp.addMapping("pm_invest_event_detail", "event_id", PmInvestEventDetail.class);
		arp.addMapping("pm_org_extend_entity" , PmOrgExtendEntity.class);
		arp.addMapping("pm_org_info", "org_id", PmOrgInfo.class);
		arp.addMapping("pm_rumor" , PmRumor.class);
		arp.addMapping("pm_startups_info", "id", PmStartupsInfo.class);
		arp.addMapping("pm_user_info" , PmUserInfo.class);
		arp.addMapping("rds_ent_holder" , RdsEntHolder.class);
		arp.addMapping("rds_ent_invest" , RdsEntInvest.class);
		arp.addMapping("rds_ent_law" , RdsEntLaw.class);
		arp.addMapping("rds_ent_mortgages" , RdsEntMortgages.class);
		arp.addMapping("rds_ent_patent" , RdsEntPatent.class);
		arp.addMapping("rpt_angel_list", "id", RptAngelList.class);
		arp.addMapping("rpt_cv" , RptCv.class);
		arp.addMapping("rpt_ent_judge_value" , RptEntJudgeValue.class);
		arp.addMapping("rpt_org_forcus_ent" , RptOrgForcusEnt.class);
		arp.addMapping("rpt_org_overall_trends" , RptOrgOverallTrends.class);
		arp.addMapping("rpt_orger_list", "id", RptOrgerList.class);
		arp.addMapping("rpt_pe_fund" , RptPeFund.class);
		arp.addMapping("rpt_toe_ma" , RptToeMa.class);
		arp.addMapping("rpt_trader" , RptTrader.class);
		arp.addMapping("stock_equityctrl" , StockEquityctrl.class);
		arp.addMapping("stock_feature_all" , StockFeatureAll.class);
		arp.addMapping("stock_feature_all_scaled" , StockFeatureAllScaled.class);
		arp.addMapping("stock_feature_all_uuid" , StockFeatureAllUuid.class);
		arp.addMapping("stock_feature_parameter" , StockFeatureParameter.class);
		arp.addMapping("stock_finance_chart" , StockFinanceChart.class);
		arp.addMapping("stock_finance_chart_industry" , StockFinanceChartIndustry.class);
		arp.addMapping("stock_holder_latest" , StockHolderLatest.class);
		arp.addMapping("stock_info", "stock_code", StockInfo.class);
		arp.addMapping("stock_inst_invest" , StockInstInvest.class);
		arp.addMapping("stock_list_potential_ma" , StockListPotentialMa.class);
		arp.addMapping("stock_manage_team" , StockManageTeam.class);
		arp.addMapping("stock_xsb_list_matching" , StockXsbListMatching.class);
	}
}

