/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cv.util.distance;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-07-01")
public class QueryResult implements org.apache.thrift.TBase<QueryResult, QueryResult._Fields>, java.io.Serializable, Cloneable, Comparable<QueryResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueryResult");

  private static final org.apache.thrift.protocol.TField VOCA_POSITION_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("vocaPositionList", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField WORD_DIST_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("wordDistList", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueryResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueryResultTupleSchemeFactory());
  }

  public List<VocabularyPosition> vocaPositionList; // required
  public List<WordDist> wordDistList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VOCA_POSITION_LIST((short)1, "vocaPositionList"),
    WORD_DIST_LIST((short)2, "wordDistList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VOCA_POSITION_LIST
          return VOCA_POSITION_LIST;
        case 2: // WORD_DIST_LIST
          return WORD_DIST_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VOCA_POSITION_LIST, new org.apache.thrift.meta_data.FieldMetaData("vocaPositionList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, VocabularyPosition.class))));
    tmpMap.put(_Fields.WORD_DIST_LIST, new org.apache.thrift.meta_data.FieldMetaData("wordDistList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, WordDist.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueryResult.class, metaDataMap);
  }

  public QueryResult() {
  }

  public QueryResult(
    List<VocabularyPosition> vocaPositionList,
    List<WordDist> wordDistList)
  {
    this();
    this.vocaPositionList = vocaPositionList;
    this.wordDistList = wordDistList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryResult(QueryResult other) {
    if (other.isSetVocaPositionList()) {
      List<VocabularyPosition> __this__vocaPositionList = new ArrayList<VocabularyPosition>(other.vocaPositionList.size());
      for (VocabularyPosition other_element : other.vocaPositionList) {
        __this__vocaPositionList.add(new VocabularyPosition(other_element));
      }
      this.vocaPositionList = __this__vocaPositionList;
    }
    if (other.isSetWordDistList()) {
      List<WordDist> __this__wordDistList = new ArrayList<WordDist>(other.wordDistList.size());
      for (WordDist other_element : other.wordDistList) {
        __this__wordDistList.add(new WordDist(other_element));
      }
      this.wordDistList = __this__wordDistList;
    }
  }

  public QueryResult deepCopy() {
    return new QueryResult(this);
  }

  @Override
  public void clear() {
    this.vocaPositionList = null;
    this.wordDistList = null;
  }

  public int getVocaPositionListSize() {
    return (this.vocaPositionList == null) ? 0 : this.vocaPositionList.size();
  }

  public java.util.Iterator<VocabularyPosition> getVocaPositionListIterator() {
    return (this.vocaPositionList == null) ? null : this.vocaPositionList.iterator();
  }

  public void addToVocaPositionList(VocabularyPosition elem) {
    if (this.vocaPositionList == null) {
      this.vocaPositionList = new ArrayList<VocabularyPosition>();
    }
    this.vocaPositionList.add(elem);
  }

  public List<VocabularyPosition> getVocaPositionList() {
    return this.vocaPositionList;
  }

  public QueryResult setVocaPositionList(List<VocabularyPosition> vocaPositionList) {
    this.vocaPositionList = vocaPositionList;
    return this;
  }

  public void unsetVocaPositionList() {
    this.vocaPositionList = null;
  }

  /** Returns true if field vocaPositionList is set (has been assigned a value) and false otherwise */
  public boolean isSetVocaPositionList() {
    return this.vocaPositionList != null;
  }

  public void setVocaPositionListIsSet(boolean value) {
    if (!value) {
      this.vocaPositionList = null;
    }
  }

  public int getWordDistListSize() {
    return (this.wordDistList == null) ? 0 : this.wordDistList.size();
  }

  public java.util.Iterator<WordDist> getWordDistListIterator() {
    return (this.wordDistList == null) ? null : this.wordDistList.iterator();
  }

  public void addToWordDistList(WordDist elem) {
    if (this.wordDistList == null) {
      this.wordDistList = new ArrayList<WordDist>();
    }
    this.wordDistList.add(elem);
  }

  public List<WordDist> getWordDistList() {
    return this.wordDistList;
  }

  public QueryResult setWordDistList(List<WordDist> wordDistList) {
    this.wordDistList = wordDistList;
    return this;
  }

  public void unsetWordDistList() {
    this.wordDistList = null;
  }

  /** Returns true if field wordDistList is set (has been assigned a value) and false otherwise */
  public boolean isSetWordDistList() {
    return this.wordDistList != null;
  }

  public void setWordDistListIsSet(boolean value) {
    if (!value) {
      this.wordDistList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VOCA_POSITION_LIST:
      if (value == null) {
        unsetVocaPositionList();
      } else {
        setVocaPositionList((List<VocabularyPosition>)value);
      }
      break;

    case WORD_DIST_LIST:
      if (value == null) {
        unsetWordDistList();
      } else {
        setWordDistList((List<WordDist>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VOCA_POSITION_LIST:
      return getVocaPositionList();

    case WORD_DIST_LIST:
      return getWordDistList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VOCA_POSITION_LIST:
      return isSetVocaPositionList();
    case WORD_DIST_LIST:
      return isSetWordDistList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryResult)
      return this.equals((QueryResult)that);
    return false;
  }

  public boolean equals(QueryResult that) {
    if (that == null)
      return false;

    boolean this_present_vocaPositionList = true && this.isSetVocaPositionList();
    boolean that_present_vocaPositionList = true && that.isSetVocaPositionList();
    if (this_present_vocaPositionList || that_present_vocaPositionList) {
      if (!(this_present_vocaPositionList && that_present_vocaPositionList))
        return false;
      if (!this.vocaPositionList.equals(that.vocaPositionList))
        return false;
    }

    boolean this_present_wordDistList = true && this.isSetWordDistList();
    boolean that_present_wordDistList = true && that.isSetWordDistList();
    if (this_present_wordDistList || that_present_wordDistList) {
      if (!(this_present_wordDistList && that_present_wordDistList))
        return false;
      if (!this.wordDistList.equals(that.wordDistList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_vocaPositionList = true && (isSetVocaPositionList());
    list.add(present_vocaPositionList);
    if (present_vocaPositionList)
      list.add(vocaPositionList);

    boolean present_wordDistList = true && (isSetWordDistList());
    list.add(present_wordDistList);
    if (present_wordDistList)
      list.add(wordDistList);

    return list.hashCode();
  }

  @Override
  public int compareTo(QueryResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetVocaPositionList()).compareTo(other.isSetVocaPositionList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVocaPositionList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vocaPositionList, other.vocaPositionList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWordDistList()).compareTo(other.isSetWordDistList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWordDistList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.wordDistList, other.wordDistList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueryResult(");
    boolean first = true;

    sb.append("vocaPositionList:");
    if (this.vocaPositionList == null) {
      sb.append("null");
    } else {
      sb.append(this.vocaPositionList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("wordDistList:");
    if (this.wordDistList == null) {
      sb.append("null");
    } else {
      sb.append(this.wordDistList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryResultStandardSchemeFactory implements SchemeFactory {
    public QueryResultStandardScheme getScheme() {
      return new QueryResultStandardScheme();
    }
  }

  private static class QueryResultStandardScheme extends StandardScheme<QueryResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueryResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VOCA_POSITION_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.vocaPositionList = new ArrayList<VocabularyPosition>(_list0.size);
                VocabularyPosition _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new VocabularyPosition();
                  _elem1.read(iprot);
                  struct.vocaPositionList.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setVocaPositionListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // WORD_DIST_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                struct.wordDistList = new ArrayList<WordDist>(_list3.size);
                WordDist _elem4;
                for (int _i5 = 0; _i5 < _list3.size; ++_i5)
                {
                  _elem4 = new WordDist();
                  _elem4.read(iprot);
                  struct.wordDistList.add(_elem4);
                }
                iprot.readListEnd();
              }
              struct.setWordDistListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueryResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.vocaPositionList != null) {
        oprot.writeFieldBegin(VOCA_POSITION_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.vocaPositionList.size()));
          for (VocabularyPosition _iter6 : struct.vocaPositionList)
          {
            _iter6.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.wordDistList != null) {
        oprot.writeFieldBegin(WORD_DIST_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.wordDistList.size()));
          for (WordDist _iter7 : struct.wordDistList)
          {
            _iter7.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryResultTupleSchemeFactory implements SchemeFactory {
    public QueryResultTupleScheme getScheme() {
      return new QueryResultTupleScheme();
    }
  }

  private static class QueryResultTupleScheme extends TupleScheme<QueryResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueryResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetVocaPositionList()) {
        optionals.set(0);
      }
      if (struct.isSetWordDistList()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetVocaPositionList()) {
        {
          oprot.writeI32(struct.vocaPositionList.size());
          for (VocabularyPosition _iter8 : struct.vocaPositionList)
          {
            _iter8.write(oprot);
          }
        }
      }
      if (struct.isSetWordDistList()) {
        {
          oprot.writeI32(struct.wordDistList.size());
          for (WordDist _iter9 : struct.wordDistList)
          {
            _iter9.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueryResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list10 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.vocaPositionList = new ArrayList<VocabularyPosition>(_list10.size);
          VocabularyPosition _elem11;
          for (int _i12 = 0; _i12 < _list10.size; ++_i12)
          {
            _elem11 = new VocabularyPosition();
            _elem11.read(iprot);
            struct.vocaPositionList.add(_elem11);
          }
        }
        struct.setVocaPositionListIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.wordDistList = new ArrayList<WordDist>(_list13.size);
          WordDist _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new WordDist();
            _elem14.read(iprot);
            struct.wordDistList.add(_elem14);
          }
        }
        struct.setWordDistListIsSet(true);
      }
    }
  }

}

