/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cv.util.distance;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-07-01")
public class VocabularyPosition implements org.apache.thrift.TBase<VocabularyPosition, VocabularyPosition._Fields>, java.io.Serializable, Cloneable, Comparable<VocabularyPosition> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("VocabularyPosition");

  private static final org.apache.thrift.protocol.TField QUERY_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("queryKey", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField POSITION_FIELD_DESC = new org.apache.thrift.protocol.TField("position", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new VocabularyPositionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new VocabularyPositionTupleSchemeFactory());
  }

  public String queryKey; // required
  public long position; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    QUERY_KEY((short)1, "queryKey"),
    POSITION((short)2, "position");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // QUERY_KEY
          return QUERY_KEY;
        case 2: // POSITION
          return POSITION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __POSITION_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.QUERY_KEY, new org.apache.thrift.meta_data.FieldMetaData("queryKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.POSITION, new org.apache.thrift.meta_data.FieldMetaData("position", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(VocabularyPosition.class, metaDataMap);
  }

  public VocabularyPosition() {
  }

  public VocabularyPosition(
    String queryKey,
    long position)
  {
    this();
    this.queryKey = queryKey;
    this.position = position;
    setPositionIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public VocabularyPosition(VocabularyPosition other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetQueryKey()) {
      this.queryKey = other.queryKey;
    }
    this.position = other.position;
  }

  public VocabularyPosition deepCopy() {
    return new VocabularyPosition(this);
  }

  @Override
  public void clear() {
    this.queryKey = null;
    setPositionIsSet(false);
    this.position = 0;
  }

  public String getQueryKey() {
    return this.queryKey;
  }

  public VocabularyPosition setQueryKey(String queryKey) {
    this.queryKey = queryKey;
    return this;
  }

  public void unsetQueryKey() {
    this.queryKey = null;
  }

  /** Returns true if field queryKey is set (has been assigned a value) and false otherwise */
  public boolean isSetQueryKey() {
    return this.queryKey != null;
  }

  public void setQueryKeyIsSet(boolean value) {
    if (!value) {
      this.queryKey = null;
    }
  }

  public long getPosition() {
    return this.position;
  }

  public VocabularyPosition setPosition(long position) {
    this.position = position;
    setPositionIsSet(true);
    return this;
  }

  public void unsetPosition() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __POSITION_ISSET_ID);
  }

  /** Returns true if field position is set (has been assigned a value) and false otherwise */
  public boolean isSetPosition() {
    return EncodingUtils.testBit(__isset_bitfield, __POSITION_ISSET_ID);
  }

  public void setPositionIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __POSITION_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case QUERY_KEY:
      if (value == null) {
        unsetQueryKey();
      } else {
        setQueryKey((String)value);
      }
      break;

    case POSITION:
      if (value == null) {
        unsetPosition();
      } else {
        setPosition((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case QUERY_KEY:
      return getQueryKey();

    case POSITION:
      return getPosition();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case QUERY_KEY:
      return isSetQueryKey();
    case POSITION:
      return isSetPosition();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof VocabularyPosition)
      return this.equals((VocabularyPosition)that);
    return false;
  }

  public boolean equals(VocabularyPosition that) {
    if (that == null)
      return false;

    boolean this_present_queryKey = true && this.isSetQueryKey();
    boolean that_present_queryKey = true && that.isSetQueryKey();
    if (this_present_queryKey || that_present_queryKey) {
      if (!(this_present_queryKey && that_present_queryKey))
        return false;
      if (!this.queryKey.equals(that.queryKey))
        return false;
    }

    boolean this_present_position = true;
    boolean that_present_position = true;
    if (this_present_position || that_present_position) {
      if (!(this_present_position && that_present_position))
        return false;
      if (this.position != that.position)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_queryKey = true && (isSetQueryKey());
    list.add(present_queryKey);
    if (present_queryKey)
      list.add(queryKey);

    boolean present_position = true;
    list.add(present_position);
    if (present_position)
      list.add(position);

    return list.hashCode();
  }

  @Override
  public int compareTo(VocabularyPosition other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetQueryKey()).compareTo(other.isSetQueryKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQueryKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.queryKey, other.queryKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPosition()).compareTo(other.isSetPosition());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPosition()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.position, other.position);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("VocabularyPosition(");
    boolean first = true;

    sb.append("queryKey:");
    if (this.queryKey == null) {
      sb.append("null");
    } else {
      sb.append(this.queryKey);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("position:");
    sb.append(this.position);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class VocabularyPositionStandardSchemeFactory implements SchemeFactory {
    public VocabularyPositionStandardScheme getScheme() {
      return new VocabularyPositionStandardScheme();
    }
  }

  private static class VocabularyPositionStandardScheme extends StandardScheme<VocabularyPosition> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, VocabularyPosition struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // QUERY_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.queryKey = iprot.readString();
              struct.setQueryKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // POSITION
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.position = iprot.readI64();
              struct.setPositionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, VocabularyPosition struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.queryKey != null) {
        oprot.writeFieldBegin(QUERY_KEY_FIELD_DESC);
        oprot.writeString(struct.queryKey);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(POSITION_FIELD_DESC);
      oprot.writeI64(struct.position);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class VocabularyPositionTupleSchemeFactory implements SchemeFactory {
    public VocabularyPositionTupleScheme getScheme() {
      return new VocabularyPositionTupleScheme();
    }
  }

  private static class VocabularyPositionTupleScheme extends TupleScheme<VocabularyPosition> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, VocabularyPosition struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetQueryKey()) {
        optionals.set(0);
      }
      if (struct.isSetPosition()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetQueryKey()) {
        oprot.writeString(struct.queryKey);
      }
      if (struct.isSetPosition()) {
        oprot.writeI64(struct.position);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, VocabularyPosition struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.queryKey = iprot.readString();
        struct.setQueryKeyIsSet(true);
      }
      if (incoming.get(1)) {
        struct.position = iprot.readI64();
        struct.setPositionIsSet(true);
      }
    }
  }

}

